// lib/locations-expanded.ts
// EXPANDED LOCATION DATABASE — 5 Regions, 200+ hyper-local areas
// Greater Manchester (10 boroughs) | Crewe & Cheshire East | Stoke-on-Trent | Liverpool & Merseyside | Carlisle & Cumbria

export type Region = 'manchester' | 'crewe' | 'stoke' | 'liverpool' | 'carlisle'

export interface LocationData {
  slug: string
  name: string
  postcode: string
  region: Region
  borough?: string          // council/borough for grouping
  tier: 1 | 2 | 3          // 1=city/town centre, 2=district, 3=village/ward
  localContext: string
  propertyTypes: string
  nearbyAreas: string[]
  lat: number
  lng: number
}

export const LOCATIONS_EXPANDED: LocationData[] = [

  // ═══════════════════════════════════════════════════════
  // GREATER MANCHESTER — All 10 Boroughs
  // ═══════════════════════════════════════════════════════

  // ── MANCHESTER CITY (Manchester City Council) ──────────
  { slug:'manchester-city-centre', name:'Manchester City Centre', postcode:'M1', region:'manchester', borough:'Manchester', tier:1, localContext:'The commercial and cultural heart of the North West, home to high-rise apartments, student accommodation, and a rapid-turnover rental market — EOT cleaning demand is exceptionally high.', propertyTypes:'City centre apartments, new-build flats, serviced accommodation, Airbnb properties', nearbyAreas:['Ancoats','Northern Quarter','Spinningfields','Deansgate'], lat:53.4808, lng:-2.2426 },
  { slug:'ancoats', name:'Ancoats', postcode:'M4', region:'manchester', borough:'Manchester', tier:2, localContext:'One of Manchester\'s most rapidly gentrifying neighbourhoods, Ancoats is packed with converted mill apartments and new-build developments attracting young professionals with high expectations.', propertyTypes:'Converted mill apartments, new-build developments, serviced flats', nearbyAreas:['Northern Quarter','Manchester City Centre','New Islington'], lat:53.4833, lng:-2.2246 },
  { slug:'northern-quarter', name:'Northern Quarter', postcode:'M4', region:'manchester', borough:'Manchester', tier:2, localContext:'Manchester\'s creative hub has a dense residential population above its bars and independent shops — a mix of tenanted flats and Airbnb lets with frequent turnovers.', propertyTypes:'Tenanted flats above commercial, loft-style apartments, Airbnb properties', nearbyAreas:['Ancoats','Manchester City Centre','Piccadilly'], lat:53.4840, lng:-2.2350 },
  { slug:'spinningfields', name:'Spinningfields', postcode:'M3', region:'manchester', borough:'Manchester', tier:2, localContext:'Manchester\'s premium business district has a growing luxury residential tower population — corporate lets and high-spec apartments requiring immaculate cleaning standards.', propertyTypes:'Luxury apartments, corporate lets, high-spec serviced apartments', nearbyAreas:['Deansgate','Manchester City Centre','Castlefield'], lat:53.4807, lng:-2.2519 },
  { slug:'deansgate', name:'Deansgate', postcode:'M3', region:'manchester', borough:'Manchester', tier:2, localContext:'Deansgate is one of Manchester\'s most desirable residential addresses, with premium apartment towers overlooking the canal — high-value properties demanding top-tier cleaning.', propertyTypes:'Premium apartment towers, canal-side flats, high-value residential', nearbyAreas:['Spinningfields','Castlefield','Manchester City Centre'], lat:53.4772, lng:-2.2512 },
  { slug:'castlefield', name:'Castlefield', postcode:'M3', region:'manchester', borough:'Manchester', tier:2, localContext:'Manchester\'s Urban Heritage Park area is popular with professionals in canal-side conversions and modern apartment blocks — strong Airbnb and EOT market.', propertyTypes:'Canal-side conversions, modern apartment blocks, professional lets', nearbyAreas:['Deansgate','Hulme','Manchester City Centre'], lat:53.4739, lng:-2.2554 },
  { slug:'piccadilly', name:'Piccadilly', postcode:'M1', region:'manchester', borough:'Manchester', tier:2, localContext:'The gateway to Manchester, Piccadilly has a dense mix of short-term lets, student properties, and newly converted apartment blocks with consistently high cleaning demand.', propertyTypes:'Short-term lets, student apartments, converted office flats', nearbyAreas:['Northern Quarter','Manchester City Centre','Ardwick'], lat:53.4776, lng:-2.2309 },
  { slug:'didsbury', name:'Didsbury', postcode:'M20', region:'manchester', borough:'Manchester', tier:1, localContext:'One of South Manchester\'s most sought-after suburbs, Didsbury has a strong private rental market of Victorian and Edwardian properties with tenants expecting high cleaning standards at checkout.', propertyTypes:'Victorian terraces, Edwardian semis, detached family homes, converted flats', nearbyAreas:['West Didsbury','Withington','Chorlton','Burnage'], lat:53.4135, lng:-2.2274 },
  { slug:'west-didsbury', name:'West Didsbury', postcode:'M20', region:'manchester', borough:'Manchester', tier:2, localContext:'The boutique end of Didsbury, West Didsbury commands premium rents and attracts professional tenants who expect an immaculate property at every checkout.', propertyTypes:'Victorian terraces, boutique flats, premium rentals', nearbyAreas:['Didsbury','Withington','Chorlton'], lat:53.4108, lng:-2.2370 },
  { slug:'chorlton', name:'Chorlton', postcode:'M21', region:'manchester', borough:'Manchester', tier:1, localContext:'Chorlton is South Manchester\'s most popular family suburb, with a large and active rental market spanning Victorian terraces to modern builds — consistently high EOT cleaning demand.', propertyTypes:'Victorian terraces, Edwardian semis, modern builds, HMOs', nearbyAreas:['Didsbury','Whalley Range','Sale','Stretford'], lat:53.4408, lng:-2.2704 },
  { slug:'withington', name:'Withington', postcode:'M20', region:'manchester', borough:'Manchester', tier:2, localContext:'Withington bridges the gap between student Fallowfield and professional Didsbury — a high-churn rental market with frequent EOT cleans needed between academic years.', propertyTypes:'Student HMOs, professional lets, converted semis', nearbyAreas:['Didsbury','Fallowfield','Burnage'], lat:53.4243, lng:-2.2264 },
  { slug:'fallowfield', name:'Fallowfield', postcode:'M14', region:'manchester', borough:'Manchester', tier:1, localContext:'Home to Manchester\'s largest student population, Fallowfield sees a massive wave of end of tenancy cleans every June and July — the biggest EOT cleaning market in South Manchester.', propertyTypes:'Student HMOs, 4-6 bed shared houses, purpose-built student blocks', nearbyAreas:['Withington','Rusholme','Levenshulme','Moss Side'], lat:53.4335, lng:-2.2172 },
  { slug:'rusholme', name:'Rusholme', postcode:'M14', region:'manchester', borough:'Manchester', tier:2, localContext:'The Curry Mile neighbourhood has dense residential streets behind its restaurant strip — a high-density rental market with strong demand for professional cleaning services.', propertyTypes:'Terraced houses, HMOs, mixed-use residential', nearbyAreas:['Fallowfield','Hulme','Moss Side'], lat:53.4503, lng:-2.2168 },
  { slug:'hulme', name:'Hulme', postcode:'M15', region:'manchester', borough:'Manchester', tier:2, localContext:'Hulme has undergone significant regeneration and now has a strong mix of social housing, new builds, and private lets close to the city centre — busy EOT and deep clean market.', propertyTypes:'New-build estates, regeneration housing, modern flats, private lets', nearbyAreas:['Castlefield','Moss Side','Manchester City Centre'], lat:53.4637, lng:-2.2560 },
  { slug:'moss-side', name:'Moss Side', postcode:'M14', region:'manchester', borough:'Manchester', tier:2, localContext:'A community-rich neighbourhood with a strong owner-occupier base and growing private rental sector — demand for reliable, locally known cleaning services is high.', propertyTypes:'Terraced houses, semis, private lets', nearbyAreas:['Hulme','Rusholme','Fallowfield'], lat:53.4516, lng:-2.2450 },
  { slug:'levenshulme', name:'Levenshulme', postcode:'M19', region:'manchester', borough:'Manchester', tier:2, localContext:'Levenshulme is attracting young professional families priced out of Didsbury — its growing rental market of Victorian terraces creates strong demand for EOT and regular cleaning.', propertyTypes:'Victorian terraces, semis, emerging professional rentals', nearbyAreas:['Didsbury','Burnage','Gorton'], lat:53.4365, lng:-2.1909 },
  { slug:'burnage', name:'Burnage', postcode:'M19', region:'manchester', borough:'Manchester', tier:2, localContext:'A quiet residential suburb between Didsbury and Levenshulme, Burnage has a stable rental market of interwar semis and terraces popular with professional tenants.', propertyTypes:'Interwar semis, terraced houses, professional family rentals', nearbyAreas:['Didsbury','Levenshulme','Withington'], lat:53.4228, lng:-2.2085 },
  { slug:'gorton', name:'Gorton', postcode:'M18', region:'manchester', borough:'Manchester', tier:2, localContext:'Gorton has a large and growing social and private rental market — with significant regeneration underway, demand for professional cleaning is increasing strongly.', propertyTypes:'Terraced houses, council properties, private lets, new builds', nearbyAreas:['Levenshulme','Longsight','Openshaw'], lat:53.4651, lng:-2.1749 },
  { slug:'longsight', name:'Longsight', postcode:'M12', region:'manchester', borough:'Manchester', tier:2, localContext:'One of Manchester\'s most diverse and densely populated inner suburbs, Longsight has a very active private rental market with consistent EOT cleaning demand throughout the year.', propertyTypes:'Terraced houses, mixed-use residential, HMOs, private lets', nearbyAreas:['Gorton','Rusholme','Ardwick'], lat:53.4548, lng:-2.1990 },
  { slug:'ardwick', name:'Ardwick', postcode:'M12', region:'manchester', borough:'Manchester', tier:2, localContext:'Close to the city centre, Ardwick is popular with students and young professionals in converted properties and new apartments — consistent cleaning demand year-round.', propertyTypes:'Converted houses, new apartments, student accommodation', nearbyAreas:['Manchester City Centre','Longsight','Piccadilly'], lat:53.4671, lng:-2.2148 },
  { slug:'whalley-range', name:'Whalley Range', postcode:'M16', region:'manchester', borough:'Manchester', tier:2, localContext:'Whalley Range is popular with families and professionals in large Victorian properties — many split into flats with active tenant turnover requiring thorough cleaning at checkout.', propertyTypes:'Large Victorian houses, converted flats, family rentals', nearbyAreas:['Chorlton','Moss Side','Old Trafford'], lat:53.4498, lng:-2.2510 },
  { slug:'old-trafford-manchester', name:'Old Trafford', postcode:'M16', region:'manchester', borough:'Manchester', tier:2, localContext:'Old Trafford\'s residential streets — separate from the stadium — have a dense rental market popular with students and young professionals near MediaCityUK.', propertyTypes:'Terraced houses, flats, student accommodation', nearbyAreas:['Stretford','Whalley Range','Salford Quays'], lat:53.4604, lng:-2.2756 },
  { slug:'wythenshawe', name:'Wythenshawe', postcode:'M22', region:'manchester', borough:'Manchester', tier:2, localContext:'One of Europe\'s largest council estates now has significant private rental activity — a large, underserved market for professional cleaning services close to Manchester Airport.', propertyTypes:'Council and ex-council houses, private lets, family homes', nearbyAreas:['Northenden','Baguley','Sale'], lat:53.3943, lng:-2.2663 },
  { slug:'northenden', name:'Northenden', postcode:'M22', region:'manchester', borough:'Manchester', tier:2, localContext:'A quiet riverside suburb on the Mersey boundary between Manchester and Stockport — popular with families in private rental properties.', propertyTypes:'Semis, detached houses, family private rentals', nearbyAreas:['Wythenshawe','Didsbury','Gatley'], lat:53.4072, lng:-2.2540 },
  { slug:'harpurhey', name:'Harpurhey', postcode:'M9', region:'manchester', borough:'Manchester', tier:2, localContext:'North Manchester neighbourhood with active private rental market and strong demand for affordable, reliable professional cleaning services.', propertyTypes:'Terraced houses, council and private lets', nearbyAreas:['Crumpsall','Collyhurst','Moston'], lat:53.5115, lng:-2.2198 },
  { slug:'crumpsall', name:'Crumpsall', postcode:'M8', region:'manchester', borough:'Manchester', tier:2, localContext:'North Manchester suburb close to North Manchester General Hospital — a stable residential area with a mix of families and professionals renting.', propertyTypes:'Semis, terraces, professional and family rentals', nearbyAreas:['Harpurhey','Prestwich','Cheetham Hill'], lat:53.5142, lng:-2.2376 },
  { slug:'cheetham-hill', name:'Cheetham Hill', postcode:'M8', region:'manchester', borough:'Manchester', tier:2, localContext:'A diverse inner North Manchester neighbourhood with a busy residential rental market and strong demand for end of tenancy cleaning.', propertyTypes:'Terraced houses, flats, HMOs, diverse rental market', nearbyAreas:['Crumpsall','Manchester City Centre','Salford'], lat:53.5044, lng:-2.2272 },
  { slug:'moston', name:'Moston', postcode:'M40', region:'manchester', borough:'Manchester', tier:2, localContext:'A large North Manchester suburb with a dense network of interwar semis and terraces in active private rental — underserved by professional cleaning businesses.', propertyTypes:'Interwar semis, terraces, private lets', nearbyAreas:['Harpurhey','Newton Heath','Collyhurst'], lat:53.5153, lng:-2.1881 },
  { slug:'newton-heath', name:'Newton Heath', postcode:'M40', region:'manchester', borough:'Manchester', tier:3, localContext:'Historic Manchester suburb undergoing gradual regeneration — a growing private rental market close to Sportcity and East Manchester investment zones.', propertyTypes:'Terraced houses, private lets, emerging new builds', nearbyAreas:['Moston','Collyhurst','Openshaw'], lat:53.4961, lng:-2.1785 },
  { slug:'new-islington', name:'New Islington', postcode:'M4', region:'manchester', borough:'Manchester', tier:2, localContext:'Manchester\'s fastest-growing new neighbourhood, built on the Ancoats canalside — modern apartments and townhouses with young professional tenants expecting premium cleaning.', propertyTypes:'Modern canal-side apartments, townhouses, premium new builds', nearbyAreas:['Ancoats','Northern Quarter','Ardwick'], lat:53.4790, lng:-2.2195 },

  // ── SALFORD (Salford City Council) ──────────
  { slug:'salford-city', name:'Salford', postcode:'M5', region:'manchester', borough:'Salford', tier:1, localContext:'Adjacent to Manchester city centre, Salford has one of the North West\'s largest rental markets — from regenerated docklands apartments to dense residential streets with high tenant churn.', propertyTypes:'Regenerated apartments, Victorian terraces, mixed rental properties', nearbyAreas:['Salford Quays','Eccles','Manchester City Centre'], lat:53.4875, lng:-2.2901 },
  { slug:'salford-quays', name:'Salford Quays', postcode:'M50', region:'manchester', borough:'Salford', tier:1, localContext:'Home to MediaCityUK, Salford Quays attracts BBC and ITV employees plus digital sector workers in premium waterfront apartments — one of Greater Manchester\'s strongest Airbnb markets.', propertyTypes:'Waterfront apartments, premium lets, Airbnb properties, corporate accommodation', nearbyAreas:['Salford','Old Trafford','Stretford'], lat:53.4721, lng:-2.2985 },
  { slug:'eccles', name:'Eccles', postcode:'M30', region:'manchester', borough:'Salford', tier:2, localContext:'Eccles town centre has a dense residential area with significant rental activity — a reliable, year-round EOT and deep cleaning market with strong letting agent presence.', propertyTypes:'Terraced houses, semis, Victorian properties, private lets', nearbyAreas:['Salford','Monton','Swinton'], lat:53.4836, lng:-2.3333 },
  { slug:'monton', name:'Monton', postcode:'M30', region:'manchester', borough:'Salford', tier:2, localContext:'Monton village is popular with young professionals priced out of Chorlton — its active private rental market of Victorian properties is growing strongly.', propertyTypes:'Victorian semis and terraces, professional rentals, family homes', nearbyAreas:['Eccles','Worsley','Boothstown'], lat:53.4813, lng:-2.3526 },
  { slug:'swinton', name:'Swinton', postcode:'M27', region:'manchester', borough:'Salford', tier:2, localContext:'A large residential suburb in the heart of Salford — busy private rental market with strong letting agent activity and consistent EOT demand.', propertyTypes:'Interwar semis, terraces, family rentals', nearbyAreas:['Eccles','Worsley','Pendlebury'], lat:53.5129, lng:-2.3399 },
  { slug:'worsley', name:'Worsley', postcode:'M28', region:'manchester', borough:'Salford', tier:2, localContext:'One of Salford\'s most desirable villages — the heritage canal village with premium family homes and executive rentals expecting the highest cleaning standards.', propertyTypes:'Executive family homes, detached properties, premium rentals', nearbyAreas:['Monton','Boothstown','Walkden'], lat:53.5013, lng:-2.3744 },
  { slug:'pendlebury', name:'Pendlebury', postcode:'M27', region:'manchester', borough:'Salford', tier:3, localContext:'Residential suburb between Salford and Swinton with a steady private rental market — ideal for regular home cleaning and EOT services.', propertyTypes:'Interwar housing, terraces, family rentals', nearbyAreas:['Swinton','Salford','Irlam'], lat:53.5180, lng:-2.3140 },

  // ── TRAFFORD (Trafford Council) ──────────
  { slug:'altrincham', name:'Altrincham', postcode:'WA14', region:'manchester', borough:'Trafford', tier:1, localContext:'Altrincham\'s regeneration has made it one of Greater Manchester\'s most desirable addresses — premium properties, high-value tenants, and strong demand for professional cleaning at the highest standards.', propertyTypes:'Victorian semis, luxury apartments, premium family homes, executive lets', nearbyAreas:['Hale','Sale','Bowdon'], lat:53.3838, lng:-2.3527 },
  { slug:'sale', name:'Sale', postcode:'M33', region:'manchester', borough:'Trafford', tier:1, localContext:'Sale is one of Trafford\'s largest residential towns with a substantial and active private rental market — family homes, apartments, and a Metrolink connection that drives tenant demand.', propertyTypes:'Family semis, detached homes, apartments, private lets', nearbyAreas:['Altrincham','Stretford','Chorlton'], lat:53.4232, lng:-2.3165 },
  { slug:'hale', name:'Hale', postcode:'WA15', region:'manchester', borough:'Trafford', tier:1, localContext:'Hale village is one of Greater Manchester\'s most affluent addresses — premium properties, demanding landlords, and tenants who expect the finest cleaning standards.', propertyTypes:'Luxury detached homes, premium semis, high-value rental properties', nearbyAreas:['Altrincham','Bowdon','Hale Barns'], lat:53.3765, lng:-2.3596 },
  { slug:'hale-barns', name:'Hale Barns', postcode:'WA15', region:'manchester', borough:'Trafford', tier:2, localContext:'An exclusive residential village adjacent to Hale — high-value owner-occupied and rented properties with a premium cleaning market.', propertyTypes:'Large detached homes, luxury properties, executive rentals', nearbyAreas:['Hale','Altrincham','Bowdon'], lat:53.3682, lng:-2.3266 },
  { slug:'bowdon', name:'Bowdon', postcode:'WA14', region:'manchester', borough:'Trafford', tier:2, localContext:'One of Cheshire\'s most prestigious villages just inside the Greater Manchester boundary — large Victorian villas and premium properties requiring top-tier cleaning services.', propertyTypes:'Large Victorian villas, premium detached homes, luxury rentals', nearbyAreas:['Altrincham','Hale','Ashley'], lat:53.3714, lng:-2.3758 },
  { slug:'stretford', name:'Stretford', postcode:'M32', region:'manchester', borough:'Trafford', tier:2, localContext:'Stretford sits at the crossroads of Manchester, Salford, and Trafford — a dense residential area with strong rental demand close to Old Trafford stadium.', propertyTypes:'Terraced houses, semis, private lets, student accommodation', nearbyAreas:['Sale','Old Trafford','Chorlton'], lat:53.4472, lng:-2.3025 },
  { slug:'urmston', name:'Urmston', postcode:'M41', region:'manchester', borough:'Trafford', tier:2, localContext:'A family-focused Trafford suburb popular with professionals commuting into Manchester — active private rental market with consistent cleaning demand.', propertyTypes:'Family semis, detached homes, private rental properties', nearbyAreas:['Eccles','Stretford','Sale'], lat:53.4468, lng:-2.3740 },
  { slug:'partington', name:'Partington', postcode:'M31', region:'manchester', borough:'Trafford', tier:3, localContext:'A large residential estate in south Trafford — underserved by professional cleaning companies despite a strong social and private rental base.', propertyTypes:'Estate housing, council and private lets, family homes', nearbyAreas:['Urmston','Sale','Carrington'], lat:53.4122, lng:-2.4261 },

  // ── STOCKPORT (Stockport Metropolitan Borough) ──────────
  { slug:'stockport-town-centre', name:'Stockport', postcode:'SK1', region:'manchester', borough:'Stockport', tier:1, localContext:'Stockport town centre is undergoing significant regeneration — a growing apartment market alongside Victorian terraces makes it one of the most active rental areas in the Stockport borough.', propertyTypes:'Town centre apartments, Victorian terraces, mixed rental', nearbyAreas:['Edgeley','Heaton Moor','Reddish'], lat:53.4068, lng:-2.1575 },
  { slug:'edgeley', name:'Edgeley', postcode:'SK3', region:'manchester', borough:'Stockport', tier:2, localContext:'Adjacent to Stockport town centre and the County Ground, Edgeley is a densely rented Victorian suburb with strong letting agent activity and consistent EOT demand.', propertyTypes:'Victorian terraces, converted flats, professional lets', nearbyAreas:['Stockport','Cheadle','Adswood'], lat:53.4000, lng:-2.1770 },
  { slug:'heaton-moor', name:'Heaton Moor', postcode:'SK4', region:'manchester', borough:'Stockport', tier:1, localContext:'The Heaton suburbs are among South Manchester\'s most desirable — large Edwardian properties in active rental demand from professionals who expect premium cleaning standards.', propertyTypes:'Edwardian semis, large family homes, premium rentals', nearbyAreas:['Heaton Chapel','Edgeley','Didsbury'], lat:53.4163, lng:-2.1854 },
  { slug:'heaton-chapel', name:'Heaton Chapel', postcode:'SK4', region:'manchester', borough:'Stockport', tier:2, localContext:'Alongside Heaton Moor, Heaton Chapel has a strong private rental market of large period properties with professional tenants expecting thorough EOT cleans.', propertyTypes:'Victorian semis, period properties, professional rentals', nearbyAreas:['Heaton Moor','Reddish','Stockport'], lat:53.4133, lng:-2.1715 },
  { slug:'cheadle', name:'Cheadle', postcode:'SK8', region:'manchester', borough:'Stockport', tier:2, localContext:'Cheadle is a large residential suburb on the Stockport/Trafford border — popular with families and professionals who rent high-quality semis and detached properties.', propertyTypes:'Semis, detached family homes, professional rentals', nearbyAreas:['Cheadle Hulme','Gatley','Altrincham'], lat:53.3936, lng:-2.2160 },
  { slug:'cheadle-hulme', name:'Cheadle Hulme', postcode:'SK8', region:'manchester', borough:'Stockport', tier:2, localContext:'One of Stockport\'s most popular family suburbs — active private rental market with strong demand for regular home cleaning and EOT services.', propertyTypes:'Family semis, detached homes, suburban rentals', nearbyAreas:['Cheadle','Bramhall','Wilmslow'], lat:53.3810, lng:-2.1893 },
  { slug:'bramhall', name:'Bramhall', postcode:'SK7', region:'manchester', borough:'Stockport', tier:2, localContext:'A premium Stockport suburb bordering Cheshire — large detached properties and executive family homes with demanding cleaning standards.', propertyTypes:'Large detached homes, executive properties, premium rentals', nearbyAreas:['Cheadle Hulme','Hazel Grove','Poynton'], lat:53.3615, lng:-2.1656 },
  { slug:'hazel-grove', name:'Hazel Grove', postcode:'SK7', region:'manchester', borough:'Stockport', tier:2, localContext:'A busy residential suburb on the A6 corridor — active private rental market with regular families and professional tenants.', propertyTypes:'Semis, terraces, family rentals', nearbyAreas:['Bramhall','Offerton','Stockport'], lat:53.3811, lng:-2.1141 },
  { slug:'marple', name:'Marple', postcode:'SK6', region:'manchester', borough:'Stockport', tier:2, localContext:'A picturesque Peak fringe town with a premium residential market — owner-occupied family homes and high-quality rentals close to the Peak District.', propertyTypes:'Family semis, detached homes, countryside rentals', nearbyAreas:['Hazel Grove','Romiley','New Mills'], lat:53.4001, lng:-2.0546 },
  { slug:'reddish', name:'Reddish', postcode:'SK5', region:'manchester', borough:'Stockport', tier:2, localContext:'On the Stockport/Manchester border, Reddish has a dense private rental market with consistent year-round EOT demand.', propertyTypes:'Terraced houses, interwar semis, private lets', nearbyAreas:['Stockport','Levenshulme','Gorton'], lat:53.4465, lng:-2.1625 },

  // ── TAMESIDE (Tameside Metropolitan Borough) ──────────
  { slug:'ashton-under-lyne', name:'Ashton-under-Lyne', postcode:'OL6', region:'manchester', borough:'Tameside', tier:1, localContext:'Tameside\'s town centre has a large residential rental market surrounding the commercial core — consistent EOT and deep cleaning demand across both Victorian properties and modern apartments.', propertyTypes:'Victorian terraces, modern apartments, private lets, HMOs', nearbyAreas:['Droylsden','Stalybridge','Denton'], lat:53.4896, lng:-2.0965 },
  { slug:'stalybridge', name:'Stalybridge', postcode:'SK15', region:'manchester', borough:'Tameside', tier:2, localContext:'A commuter town on the edge of the Peak District — growing private rental market as buyers priced out of Manchester look east.', propertyTypes:'Victorian terraces, hill-side properties, affordable rentals', nearbyAreas:['Ashton-under-Lyne','Hyde','Mossley'], lat:53.4833, lng:-2.0560 },
  { slug:'hyde', name:'Hyde', postcode:'SK14', region:'manchester', borough:'Tameside', tier:2, localContext:'Hyde has a large, affordable private rental market with consistent EOT demand — popular with families priced out of more expensive areas.', propertyTypes:'Terraced houses, semis, affordable family rentals', nearbyAreas:['Denton','Stalybridge','Glossop'], lat:53.4525, lng:-2.0806 },
  { slug:'denton', name:'Denton', postcode:'M34', region:'manchester', borough:'Tameside', tier:2, localContext:'On the Manchester/Tameside boundary, Denton has a strong and active private rental market of interwar semis close to the A57 corridor.', propertyTypes:'Interwar semis, terraces, family rentals', nearbyAreas:['Hyde','Reddish','Droylsden'], lat:53.4555, lng:-2.1195 },
  { slug:'droylsden', name:'Droylsden', postcode:'M43', region:'manchester', borough:'Tameside', tier:2, localContext:'Between Manchester city and Tameside, Droylsden has a dense residential rental market popular with young families and professionals.', propertyTypes:'Terraced houses, semis, private lets', nearbyAreas:['Denton','Ashton-under-Lyne','Gorton'], lat:53.4789, lng:-2.1502 },

  // ── WIGAN (Wigan Metropolitan Borough) ──────────
  { slug:'wigan', name:'Wigan', postcode:'WN1', region:'manchester', borough:'Wigan', tier:1, localContext:'Wigan town centre has a large and active private rental market — strong demand for professional EOT and deep cleaning services across a wide range of property types.', propertyTypes:'Victorian terraces, new build estates, flats, private lets', nearbyAreas:['Leigh','Standish','Hindley'], lat:53.5450, lng:-2.6326 },
  { slug:'leigh', name:'Leigh', postcode:'WN7', region:'manchester', borough:'Wigan', tier:2, localContext:'Leigh has a dense residential rental market between Wigan and Manchester — consistent cleaning demand across affordable family homes.', propertyTypes:'Terraced houses, semis, family rentals', nearbyAreas:['Wigan','Atherton','Worsley'], lat:53.4961, lng:-2.5126 },
  { slug:'atherton', name:'Atherton', postcode:'M46', region:'manchester', borough:'Wigan', tier:2, localContext:'A large residential town with active private rental market — increasingly popular with first-time renters and young families.', propertyTypes:'Terraced houses, semis, family rentals', nearbyAreas:['Leigh','Wigan','Worsley'], lat:53.5224, lng:-2.4932 },

  // ── BOLTON (Bolton Metropolitan Borough) ──────────
  { slug:'bolton', name:'Bolton', postcode:'BL1', region:'manchester', borough:'Bolton', tier:1, localContext:'Bolton town centre has a large private rental market with significant letting agent activity — consistent EOT demand throughout the year.', propertyTypes:'Victorian terraces, town centre flats, private lets, HMOs', nearbyAreas:['Farnworth','Horwich','Westhoughton'], lat:53.5780, lng:-2.4282 },
  { slug:'farnworth', name:'Farnworth', postcode:'BL4', region:'manchester', borough:'Bolton', tier:2, localContext:'A large residential suburb south of Bolton with active private rental market and strong EOT cleaning demand.', propertyTypes:'Terraced houses, semis, private lets', nearbyAreas:['Bolton','Kearsley','Radcliffe'], lat:53.5459, lng:-2.3985 },
  { slug:'horwich', name:'Horwich', postcode:'BL6', region:'manchester', borough:'Bolton', tier:2, localContext:'A fast-growing commuter town near the A6, Horwich has significant new-build development and a growing private rental sector.', propertyTypes:'New build estates, semis, family rentals', nearbyAreas:['Bolton','Westhoughton','Adlington'], lat:53.5929, lng:-2.5414 },

  // ── BURY (Bury Metropolitan Borough) ──────────
  { slug:'bury', name:'Bury', postcode:'BL9', region:'manchester', borough:'Bury', tier:1, localContext:'Bury is famous for its market and has a large residential rental market across its town centre and surrounding areas — strong EOT and regular cleaning demand.', propertyTypes:'Victorian terraces, semis, town centre flats, private lets', nearbyAreas:['Radcliffe','Ramsbottom','Whitefield'], lat:53.5933, lng:-2.2963 },
  { slug:'prestwich', name:'Prestwich', postcode:'M25', region:'manchester', borough:'Bury', tier:1, localContext:'Prestwich straddles the Manchester/Bury boundary and has one of the North Manchester area\'s strongest private rental markets — popular with Jewish families and professionals.', propertyTypes:'Large semis, detached homes, premium rentals, family properties', nearbyAreas:['Bury','Whitefield','Crumpsall'], lat:53.5349, lng:-2.2832 },
  { slug:'whitefield', name:'Whitefield', postcode:'M45', region:'manchester', borough:'Bury', tier:2, localContext:'A residential suburb north of Prestwich with a strong and active private rental market — consistent cleaning demand from professional and family tenants.', propertyTypes:'Semis, family homes, private rentals', nearbyAreas:['Prestwich','Bury','Radcliffe'], lat:53.5516, lng:-2.2937 },
  { slug:'radcliffe', name:'Radcliffe', postcode:'M26', region:'manchester', borough:'Bury', tier:2, localContext:'A large Bury suburb on the River Irwell — busy private rental market close to Metrolink with consistent EOT and deep cleaning demand.', propertyTypes:'Terraced houses, semis, private lets', nearbyAreas:['Bury','Whitefield','Farnworth'], lat:53.5598, lng:-2.3262 },

  // ── OLDHAM (Oldham Metropolitan Borough) ──────────
  { slug:'oldham', name:'Oldham', postcode:'OL1', region:'manchester', borough:'Oldham', tier:1, localContext:'Oldham has one of Greater Manchester\'s largest and most diverse private rental markets — strong demand for professional cleaning services across its varied residential areas.', propertyTypes:'Victorian mill terraces, semis, diverse private lets, HMOs', nearbyAreas:['Failsworth','Chadderton','Royton'], lat:53.5409, lng:-2.1114 },
  { slug:'failsworth', name:'Failsworth', postcode:'M35', region:'manchester', borough:'Oldham', tier:2, localContext:'On the Manchester/Oldham boundary, Failsworth has an active private rental market close to the new Metrolink extension.', propertyTypes:'Interwar semis, terraces, private lets', nearbyAreas:['Oldham','Moston','Newton Heath'], lat:53.5094, lng:-2.1584 },
  { slug:'chadderton', name:'Chadderton', postcode:'OL9', region:'manchester', borough:'Oldham', tier:2, localContext:'A large Oldham suburb with a stable family rental market and consistent demand for home cleaning and EOT services.', propertyTypes:'Semis, family homes, private lets', nearbyAreas:['Oldham','Failsworth','Royton'], lat:53.5340, lng:-2.1420 },

  // ── ROCHDALE (Rochdale Metropolitan Borough) ──────────
  { slug:'rochdale', name:'Rochdale', postcode:'OL11', region:'manchester', borough:'Rochdale', tier:1, localContext:'Rochdale has a large and varied private rental market across its town centre and suburban areas — strong EOT demand especially near the Metrolink line.', propertyTypes:'Victorian terraces, town centre flats, diverse private lets, HMOs', nearbyAreas:['Heywood','Middleton','Littleborough'], lat:53.6097, lng:-2.1561 },
  { slug:'heywood', name:'Heywood', postcode:'OL10', region:'manchester', borough:'Rochdale', tier:2, localContext:'Between Rochdale and Bury, Heywood has an active private rental market with consistent demand for professional cleaning services.', propertyTypes:'Terraces, semis, family rentals', nearbyAreas:['Rochdale','Bury','Middleton'], lat:53.5917, lng:-2.2284 },
  { slug:'middleton', name:'Middleton', postcode:'M24', region:'manchester', borough:'Rochdale', tier:2, localContext:'Middleton is a large residential town on the Rochdale/Manchester border — active private rental market with strong EOT demand.', propertyTypes:'Semis, terraces, family rentals', nearbyAreas:['Rochdale','Heywood','Oldham'], lat:53.5551, lng:-2.1952 },

  // ═══════════════════════════════════════════════════════
  // CREWE & CHESHIRE EAST
  // ═══════════════════════════════════════════════════════

  { slug:'crewe', name:'Crewe', postcode:'CW1', region:'crewe', borough:'Cheshire East', tier:1, localContext:'Crewe is a major railway junction town with a large and diverse private rental market — high tenant turnover and consistent EOT cleaning demand year-round.', propertyTypes:'Victorian terraces, interwar semis, private lets, HMOs', nearbyAreas:['Nantwich','Sandbach','Haslington','Wistaston'], lat:53.0936, lng:-2.4418 },
  { slug:'crewe-west', name:'Crewe West', postcode:'CW2', region:'crewe', borough:'Cheshire East', tier:2, localContext:'The western side of Crewe including Coppenhall and Sydney — residential streets with strong private rental activity and consistent EOT demand.', propertyTypes:'Victorian terraces, semis, family rentals', nearbyAreas:['Crewe','Wistaston','Shavington'], lat:53.0894, lng:-2.4604 },
  { slug:'crewe-east', name:'Crewe East', postcode:'CW1', region:'crewe', borough:'Cheshire East', tier:2, localContext:'The eastern residential wards of Crewe including Maw Green and Leighton — active private rental market close to the Crewe Heritage Centre.', propertyTypes:'Estate housing, private lets, family homes', nearbyAreas:['Crewe','Haslington','Sandbach'], lat:53.0970, lng:-2.4086 },
  { slug:'nantwich', name:'Nantwich', postcode:'CW5', region:'crewe', borough:'Cheshire East', tier:1, localContext:'A beautiful Cheshire market town with a premium residential market — high-value homes and discerning tenants expecting the finest cleaning standards.', propertyTypes:'Tudor and Georgian townhouses, premium semis, rural cottages, executive rentals', nearbyAreas:['Crewe','Wrenbury','Audlem','Bunbury'], lat:53.0664, lng:-2.5231 },
  { slug:'sandbach', name:'Sandbach', postcode:'CW11', region:'crewe', borough:'Cheshire East', tier:1, localContext:'A growing Cheshire town popular with families priced out of Nantwich and Alderley Edge — strong private rental market and consistent cleaning demand.', propertyTypes:'New build estates, semis, family homes, professional rentals', nearbyAreas:['Crewe','Middlewich','Alsager','Congleton'], lat:53.1445, lng:-2.3678 },
  { slug:'middlewich', name:'Middlewich', postcode:'CW10', region:'crewe', borough:'Cheshire East', tier:2, localContext:'A canal-side market town with a growing residential rental market — popular with families and professionals mid-way between Crewe and Knutsford.', propertyTypes:'Semis, family homes, canal-side properties, private lets', nearbyAreas:['Sandbach','Crewe','Holmes Chapel','Winsford'], lat:53.1889, lng:-2.4396 },
  { slug:'alsager', name:'Alsager', postcode:'ST7', region:'crewe', borough:'Cheshire East', tier:2, localContext:'On the Cheshire/Staffordshire border, Alsager is a desirable commuter town with active private rental market close to Crewe and Stoke.', propertyTypes:'Semis, detached family homes, professional rentals', nearbyAreas:['Crewe','Sandbach','Kidsgrove'], lat:53.0954, lng:-2.3047 },
  { slug:'haslington', name:'Haslington', postcode:'CW1', region:'crewe', borough:'Cheshire East', tier:2, localContext:'A village on the eastern edge of Crewe with growing residential development — strong family rental market and consistent cleaning demand.', propertyTypes:'New build estates, semis, village homes', nearbyAreas:['Crewe','Sandbach','Barthomley'], lat:53.0859, lng:-2.3919 },
  { slug:'wistaston', name:'Wistaston', postcode:'CW2', region:'crewe', borough:'Cheshire East', tier:2, localContext:'A desirable residential village immediately south of Crewe — popular with professional families seeking better quality housing close to Crewe\'s transport links.', propertyTypes:'Executive semis, detached family homes, premium rentals', nearbyAreas:['Crewe','Nantwich','Shavington'], lat:53.0688, lng:-2.4536 },
  { slug:'shavington', name:'Shavington', postcode:'CW2', region:'crewe', borough:'Cheshire East', tier:2, localContext:'Between Crewe and Nantwich, Shavington has significant new-build development and a growing family rental market.', propertyTypes:'New build estates, semis, family homes', nearbyAreas:['Crewe','Nantwich','Wistaston'], lat:53.0621, lng:-2.4292 },
  { slug:'wrenbury', name:'Wrenbury', postcode:'CW5', region:'crewe', borough:'Cheshire East', tier:3, localContext:'A picturesque South Cheshire village close to Nantwich — rural cottages and village properties popular with premium tenants.', propertyTypes:'Rural cottages, village properties, premium rentals', nearbyAreas:['Nantwich','Audlem','Whitchurch'], lat:53.0073, lng:-2.5600 },
  { slug:'audlem', name:'Audlem', postcode:'CW3', region:'crewe', borough:'Cheshire East', tier:3, localContext:'A popular South Cheshire canal village with a premium rural property market — regular cleaning and property maintenance demand from second homeowners.', propertyTypes:'Canal-side cottages, village houses, rural premium properties', nearbyAreas:['Nantwich','Market Drayton'], lat:52.9879, lng:-2.5078 },
  { slug:'bunbury', name:'Bunbury', postcode:'CW6', region:'crewe', borough:'Cheshire East', tier:3, localContext:'An idyllic mid-Cheshire village popular with professional families — premium rural residential market with strong demand for regular home cleaning.', propertyTypes:'Village houses, rural semis, premium family homes', nearbyAreas:['Nantwich','Tarporley','Crewe'], lat:53.1140, lng:-2.6042 },
  { slug:'tarporley', name:'Tarporley', postcode:'CW6', region:'crewe', borough:'Cheshire East', tier:2, localContext:'One of mid-Cheshire\'s most desirable small towns — premium properties, affluent residents, and strong demand for top-tier cleaning services.', propertyTypes:'Georgian townhouses, detached family homes, premium rural properties', nearbyAreas:['Bunbury','Nantwich','Northwich'], lat:53.1647, lng:-2.6694 },
  { slug:'holmes-chapel', name:'Holmes Chapel', postcode:'CW4', region:'crewe', borough:'Cheshire East', tier:2, localContext:'A desirable Cheshire village on the A50 corridor — growing family residential market popular with professionals commuting between Manchester and the Potteries.', propertyTypes:'Semis, detached family homes, professional rentals', nearbyAreas:['Middlewich','Sandbach','Knutsford'], lat:53.2011, lng:-2.3543 },
  { slug:'congleton', name:'Congleton', postcode:'CW12', region:'crewe', borough:'Cheshire East', tier:2, localContext:'A market town in the east of Cheshire East with a strong private rental market — popular with families and professionals working across Cheshire and Staffordshire.', propertyTypes:'Victorian terraces, semis, family homes, private lets', nearbyAreas:['Sandbach','Macclesfield','Alsager'], lat:53.1630, lng:-2.2142 },
  { slug:'macclesfield', name:'Macclesfield', postcode:'SK10', region:'crewe', borough:'Cheshire East', tier:1, localContext:'East Cheshire\'s largest town has a significant private rental market across its Victorian streets and modern developments — strong EOT and deep cleaning demand.', propertyTypes:'Victorian terraces, modern apartments, premium semis, private lets', nearbyAreas:['Wilmslow','Bollington','Prestbury','Congleton'], lat:53.2598, lng:-2.1267 },
  { slug:'wilmslow', name:'Wilmslow', postcode:'SK9', region:'crewe', borough:'Cheshire East', tier:1, localContext:'One of Cheshire\'s most prestigious addresses — footballer belt territory with large detached homes, gated developments, and the highest cleaning standards in the region.', propertyTypes:'Large detached homes, gated developments, luxury properties, executive rentals', nearbyAreas:['Alderley Edge','Handforth','Cheadle Hulme'], lat:53.3271, lng:-2.2307 },
  { slug:'alderley-edge', name:'Alderley Edge', postcode:'SK9', region:'crewe', borough:'Cheshire East', tier:1, localContext:'The most exclusive village in Cheshire — home to Premier League footballers and business executives, with a premium cleaning market that demands the absolute highest standards.', propertyTypes:'Luxury detached mansions, executive properties, premium gated developments', nearbyAreas:['Wilmslow','Prestbury','Macclesfield'], lat:53.3046, lng:-2.2261 },
  { slug:'prestbury', name:'Prestbury', postcode:'SK10', region:'crewe', borough:'Cheshire East', tier:2, localContext:'Consistently voted one of England\'s wealthiest villages — ultra-premium residential properties requiring immaculate cleaning to the highest possible standards.', propertyTypes:'Country houses, executive properties, ultra-premium residential', nearbyAreas:['Macclesfield','Alderley Edge','Bollington'], lat:53.2942, lng:-2.1505 },
  { slug:'knutsford', name:'Knutsford', postcode:'WA16', region:'crewe', borough:'Cheshire East', tier:1, localContext:'A beautiful Cheshire market town — premium residential market across Georgian townhouses and countryside properties, with affluent tenants and homeowners expecting excellence.', propertyTypes:'Georgian townhouses, countryside semis, premium rentals, executive properties', nearbyAreas:['Wilmslow','Altrincham','Holmes Chapel'], lat:53.3027, lng:-2.3699 },
  { slug:'handforth', name:'Handforth', postcode:'SK9', region:'crewe', borough:'Cheshire East', tier:2, localContext:'Between Wilmslow and Cheadle Hulme, Handforth has a strong family residential market with good transport links — active private rental market.', propertyTypes:'Family semis, detached homes, private rentals', nearbyAreas:['Wilmslow','Cheadle Hulme','Poynton'], lat:53.3558, lng:-2.2163 },
  { slug:'disley', name:'Disley', postcode:'SK12', region:'crewe', borough:'Cheshire East', tier:3, localContext:'A Peak District gateway village on the Cheshire/Derbyshire border — popular with professional families in premium rural properties.', propertyTypes:'Countryside cottages, village properties, premium family homes', nearbyAreas:['Poynton','Hazel Grove','New Mills'], lat:53.3542, lng:-2.0480 },
  { slug:'bollington', name:'Bollington', postcode:'SK10', region:'crewe', borough:'Cheshire East', tier:3, localContext:'A pretty mill town on the Macclesfield fringe of the Peak District — popular with professionals and creatives in converted mill properties and village houses.', propertyTypes:'Converted mill properties, village houses, professional lets', nearbyAreas:['Macclesfield','Prestbury','Disley'], lat:53.2922, lng:-2.1066 },
  { slug:'winsford', name:'Winsford', postcode:'CW7', region:'crewe', borough:'Cheshire East', tier:2, localContext:'A large Cheshire East town with a significant private rental market — consistent cleaning demand from families and professionals.', propertyTypes:'Estate housing, semis, private lets, family homes', nearbyAreas:['Middlewich','Northwich','Tarporley'], lat:53.1988, lng:-2.5248 },

  // ═══════════════════════════════════════════════════════
  // STOKE-ON-TRENT & SURROUNDING STAFFORDSHIRE
  // ═══════════════════════════════════════════════════════

  { slug:'hanley', name:'Hanley', postcode:'ST1', region:'stoke', borough:'Stoke-on-Trent', tier:1, localContext:'The commercial heart of Stoke-on-Trent, Hanley has a large student and young professional rental market concentrated around the city centre and Staffordshire University — high EOT demand each summer.', propertyTypes:'City centre flats, student accommodation, HMOs, converted properties', nearbyAreas:['Shelton','Cobridge','Sneyd Green','Burslem'], lat:53.0243, lng:-2.1730 },
  { slug:'shelton', name:'Shelton', postcode:'ST4', region:'stoke', borough:'Stoke-on-Trent', tier:2, localContext:'Home to Staffordshire University\'s main campus, Shelton has one of the highest densities of student rental properties in Staffordshire — peak EOT demand every June.', propertyTypes:'Student HMOs, shared houses, university-area private lets', nearbyAreas:['Hanley','Stoke','Basford'], lat:53.0185, lng:-2.1853 },
  { slug:'stoke', name:'Stoke', postcode:'ST4', region:'stoke', borough:'Stoke-on-Trent', tier:1, localContext:'The original town of Stoke-on-Trent around the railway station — a dense residential area with a strong and varied private rental market.', propertyTypes:'Victorian terraces, semis, private lets, mixed residential', nearbyAreas:['Fenton','Penkhull','Shelton','Hartshill'], lat:53.0022, lng:-2.1792 },
  { slug:'fenton', name:'Fenton', postcode:'ST4', region:'stoke', borough:'Stoke-on-Trent', tier:2, localContext:'Between Stoke and Longton, Fenton has a large and affordable private rental market — consistent EOT and deep cleaning demand from families and young professionals.', propertyTypes:'Victorian terraces, affordable private lets, family homes', nearbyAreas:['Stoke','Longton','Blurton'], lat:52.9983, lng:-2.1530 },
  { slug:'longton', name:'Longton', postcode:'ST3', region:'stoke', borough:'Stoke-on-Trent', tier:1, localContext:'One of the Six Towns of Stoke-on-Trent, Longton has a large residential area with active private rental market — well known for its pottery heritage and now growing rental sector.', propertyTypes:'Victorian terraces, semis, private lets, mixed residential', nearbyAreas:['Fenton','Meir','Blurton'], lat:52.9876, lng:-2.1366 },
  { slug:'meir', name:'Meir', postcode:'ST3', region:'stoke', borough:'Stoke-on-Trent', tier:2, localContext:'A large residential suburb in south Stoke-on-Trent — dense private rental market with consistent EOT cleaning demand.', propertyTypes:'Interwar semis, terraces, family rentals', nearbyAreas:['Longton','Blurton','Weston Coyney'], lat:52.9754, lng:-2.1105 },
  { slug:'blurton', name:'Blurton', postcode:'ST3', region:'stoke', borough:'Stoke-on-Trent', tier:2, localContext:'South Stoke residential suburb with a large owner-occupier and rental mix — demand for both regular home cleaning and EOT services.', propertyTypes:'Interwar semis, council and private lets, family homes', nearbyAreas:['Longton','Meir','Trentham'], lat:52.9848, lng:-2.1733 },
  { slug:'trentham', name:'Trentham', postcode:'ST4', region:'stoke', borough:'Stoke-on-Trent', tier:2, localContext:'One of Stoke\'s most desirable residential areas adjacent to Trentham Gardens — premium properties and professional tenants expecting high cleaning standards.', propertyTypes:'Premium semis, detached family homes, executive rentals', nearbyAreas:['Stoke','Blurton','Newcastle-under-Lyme'], lat:52.9656, lng:-2.2009 },
  { slug:'penkhull', name:'Penkhull', postcode:'ST4', region:'stoke', borough:'Stoke-on-Trent', tier:2, localContext:'A desirable hilltop village close to the Royal Stoke University Hospital — popular with medical professionals and university staff in private rentals.', propertyTypes:'Victorian villas, professional rentals, family homes', nearbyAreas:['Stoke','Hartshill','Newcastle-under-Lyme'], lat:53.0000, lng:-2.2000 },
  { slug:'hartshill', name:'Hartshill', postcode:'ST4', region:'stoke', borough:'Stoke-on-Trent', tier:2, localContext:'Adjacent to the Royal Stoke University Hospital and Keele University — major demand driver for professional rentals and consistent cleaning services.', propertyTypes:'Professional and medical staff lets, private rentals, family homes', nearbyAreas:['Penkhull','Newcastle-under-Lyme','Stoke'], lat:53.0105, lng:-2.2100 },
  { slug:'burslem', name:'Burslem', postcode:'ST6', region:'stoke', borough:'Stoke-on-Trent', tier:2, localContext:'The Mother Town of the Potteries has significant residential rental activity — a large working population and active private rental market.', propertyTypes:'Victorian terraces, mixed private lets, family rentals', nearbyAreas:['Tunstall','Hanley','Cobridge'], lat:53.0458, lng:-2.1870 },
  { slug:'tunstall', name:'Tunstall', postcode:'ST6', region:'stoke', borough:'Stoke-on-Trent', tier:2, localContext:'Northernmost of the Six Towns, Tunstall has a large and affordable residential rental market — consistent demand for professional cleaning services.', propertyTypes:'Victorian terraces, affordable private lets, family rentals', nearbyAreas:['Burslem','Kidsgrove','Chell'], lat:53.0609, lng:-2.2002 },
  { slug:'cobridge', name:'Cobridge', postcode:'ST6', region:'stoke', borough:'Stoke-on-Trent', tier:2, localContext:'Between Hanley and Burslem, Cobridge has dense residential streets with active private rental market.', propertyTypes:'Victorian terraces, HMOs, private lets', nearbyAreas:['Hanley','Burslem','Sneyd Green'], lat:53.0364, lng:-2.1864 },
  { slug:'bentilee', name:'Bentilee', postcode:'ST2', region:'stoke', borough:'Stoke-on-Trent', tier:2, localContext:'One of Europe\'s largest council estates, Bentilee has seen significant privatisation — a large and active social and private rental market in east Stoke.', propertyTypes:'Council and ex-council houses, private lets, family homes', nearbyAreas:['Abbey Hulton','Bucknall','Hanley'], lat:53.0166, lng:-2.1399 },
  { slug:'bucknall', name:'Bucknall', postcode:'ST2', region:'stoke', borough:'Stoke-on-Trent', tier:2, localContext:'An inner east Stoke suburb with large residential estates and consistent private rental activity.', propertyTypes:'Estate housing, semis, private lets', nearbyAreas:['Bentilee','Hanley','Abbey Hulton'], lat:53.0225, lng:-2.1550 },
  { slug:'newcastle-under-lyme', name:'Newcastle-under-Lyme', postcode:'ST5', region:'stoke', borough:'Newcastle-under-Lyme', tier:1, localContext:'Adjacent to Keele University and the Royal Stoke University Hospital, Newcastle-under-Lyme has one of North Staffordshire\'s strongest student and professional rental markets.', propertyTypes:'Student HMOs, professional lets, family semis, town centre flats', nearbyAreas:['Keele','Stoke','Trentham','Alsager'], lat:53.0109, lng:-2.2285 },
  { slug:'keele', name:'Keele', postcode:'ST5', region:'stoke', borough:'Newcastle-under-Lyme', tier:2, localContext:'Home to Keele University — one of the UK\'s most campus-based universities with a large student population requiring EOT cleans at the end of every academic year.', propertyTypes:'Student private lets, academic staff rentals, village properties', nearbyAreas:['Newcastle-under-Lyme','Stoke','Madeley'], lat:53.0033, lng:-2.2734 },
  { slug:'kidsgrove', name:'Kidsgrove', postcode:'ST7', region:'stoke', borough:'Newcastle-under-Lyme', tier:2, localContext:'On the Staffordshire/Cheshire border close to Alsager — active private rental market with consistent EOT demand from families and commuters.', propertyTypes:'Terraced houses, semis, family rentals', nearbyAreas:['Alsager','Newcastle-under-Lyme','Biddulph'], lat:53.0864, lng:-2.2410 },
  { slug:'stone-staffordshire', name:'Stone', postcode:'ST15', region:'stoke', borough:'Stafford', tier:2, localContext:'A pleasant Staffordshire market town between Stoke and Stafford — active private rental market with families and professionals.', propertyTypes:'Georgian townhouses, semis, family rentals', nearbyAreas:['Newcastle-under-Lyme','Stafford','Eccleshall'], lat:52.9028, lng:-2.1490 },
  { slug:'stafford', name:'Stafford', postcode:'ST16', region:'stoke', borough:'Stafford', tier:1, localContext:'The county town of Staffordshire has a large professional and family rental market — consistent EOT and deep cleaning demand across a wide range of property types.', propertyTypes:'Victorian terraces, family semis, town centre flats, professional lets', nearbyAreas:['Stone','Newport','Rugeley'], lat:52.8050, lng:-2.1183 },

  // ═══════════════════════════════════════════════════════
  // LIVERPOOL & MERSEYSIDE
  // ═══════════════════════════════════════════════════════

  { slug:'liverpool-city-centre', name:'Liverpool City Centre', postcode:'L1', region:'liverpool', borough:'Liverpool', tier:1, localContext:'Liverpool\'s rapidly growing city centre has a booming apartment rental market — Airbnb, student lets, and professional accommodation create some of the highest cleaning turnover rates in the North West.', propertyTypes:'City centre apartments, serviced accommodation, Airbnb properties, luxury flats', nearbyAreas:['Baltic Triangle','Ropewalks','Everton','Vauxhall'], lat:53.4084, lng:-2.9916 },
  { slug:'baltic-triangle', name:'Baltic Triangle', postcode:'L1', region:'liverpool', borough:'Liverpool', tier:2, localContext:'Liverpool\'s creative and digital quarter is now one of its hottest residential postcodes — Airbnb and short-term let density is extremely high in this converted warehouse district.', propertyTypes:'Converted warehouse apartments, new-build flats, Airbnb short-lets', nearbyAreas:['Liverpool City Centre','Toxteth','Dingle'], lat:53.4006, lng:-2.9860 },
  { slug:'ropewalks', name:'Ropewalks', postcode:'L1', region:'liverpool', borough:'Liverpool', tier:2, localContext:'Liverpool\'s nightlife and arts district has a dense residential population above its bars — student lets and professional apartments with high turnover rates.', propertyTypes:'Apartments, student lets, professional accommodation', nearbyAreas:['Liverpool City Centre','Baltic Triangle'], lat:53.4050, lng:-2.9836 },
  { slug:'everton', name:'Everton', postcode:'L5', region:'liverpool', borough:'Liverpool', tier:2, localContext:'A historic inner Liverpool neighbourhood undergoing significant regeneration — a large private rental market and growing demand for professional cleaning.', propertyTypes:'Victorian terraces, regenerated properties, private lets', nearbyAreas:['Liverpool City Centre','Anfield','Walton'], lat:53.4173, lng:-2.9681 },
  { slug:'anfield', name:'Anfield', postcode:'L4', region:'liverpool', borough:'Liverpool', tier:2, localContext:'Home to Liverpool FC, Anfield has a large residential rental market and growing Airbnb sector on match-day weekends — consistent cleaning demand.', propertyTypes:'Victorian terraces, private lets, match-day Airbnb properties', nearbyAreas:['Everton','Walton','Kirkdale'], lat:53.4308, lng:-2.9608 },
  { slug:'walton-liverpool', name:'Walton', postcode:'L9', region:'liverpool', borough:'Liverpool', tier:2, localContext:'A large north Liverpool residential suburb with active private rental market — consistent EOT and deep cleaning demand throughout the year.', propertyTypes:'Victorian terraces, interwar semis, private lets', nearbyAreas:['Anfield','Kirkdale','Fazakerley'], lat:53.4501, lng:-2.9481 },
  { slug:'kirkdale', name:'Kirkdale', postcode:'L20', region:'liverpool', borough:'Liverpool', tier:2, localContext:'Inner north Liverpool with significant private rental activity and consistent demand for professional cleaning services.', propertyTypes:'Terraced houses, private lets, mixed residential', nearbyAreas:['Walton','Everton','Bootle'], lat:53.4344, lng:-2.9951 },
  { slug:'toxteth', name:'Toxteth', postcode:'L8', region:'liverpool', borough:'Liverpool', tier:2, localContext:'Liverpool 8 is one of the city\'s most architecturally rich and diverse areas — Georgian townhouses split into flats, plus growing professional rental demand close to the universities.', propertyTypes:'Georgian townhouse conversions, student lets, professional flats', nearbyAreas:['Baltic Triangle','Dingle','Sefton Park'], lat:53.3897, lng:-2.9768 },
  { slug:'dingle', name:'Dingle', postcode:'L8', region:'liverpool', borough:'Liverpool', tier:2, localContext:'Alongside Toxteth, Dingle has a dense residential rental market close to Sefton Park — popular with students and young professionals.', propertyTypes:'Victorian terraces, student lets, professional rentals', nearbyAreas:['Toxteth','Sefton Park','Aigburth'], lat:53.3836, lng:-2.9857 },
  { slug:'edge-hill', name:'Edge Hill', postcode:'L7', region:'liverpool', borough:'Liverpool', tier:2, localContext:'Home to Liverpool\'s largest student population close to the three major universities — peak EOT demand every June makes this one of the highest-volume cleaning markets in Merseyside.', propertyTypes:'Student HMOs, shared houses, university-area private lets, purpose-built student blocks', nearbyAreas:['Kensington','Wavertree','Liverpool City Centre'], lat:53.4043, lng:-2.9558 },
  { slug:'kensington-liverpool', name:'Kensington', postcode:'L7', region:'liverpool', borough:'Liverpool', tier:2, localContext:'Between Edge Hill and the city centre, Kensington has a dense student and young professional rental market close to Liverpool John Moores and Liverpool Hope universities.', propertyTypes:'Student HMOs, professional flats, converted Victorian houses', nearbyAreas:['Edge Hill','Wavertree','Fairfield'], lat:53.4099, lng:-2.9558 },
  { slug:'wavertree', name:'Wavertree', postcode:'L15', region:'liverpool', borough:'Liverpool', tier:2, localContext:'A popular Liverpool suburb with a strong private rental market — large Victorian houses popular with professional sharers and families between the universities and the suburbs.', propertyTypes:'Victorian semis, professional sharers, family lets', nearbyAreas:['Edge Hill','Childwall','Broadgreen'], lat:53.3994, lng:-2.9294 },
  { slug:'sefton-park', name:'Sefton Park', postcode:'L17', region:'liverpool', borough:'Liverpool', tier:1, localContext:'One of Liverpool\'s most desirable residential addresses surrounding the famous Victorian park — premium Victorian properties with professional and family tenants expecting top-tier cleaning.', propertyTypes:'Large Victorian houses, premium flats, professional and family rentals', nearbyAreas:['Aigburth','Toxteth','Allerton'], lat:53.3839, lng:-2.9517 },
  { slug:'aigburth', name:'Aigburth', postcode:'L17', region:'liverpool', borough:'Liverpool', tier:1, localContext:'Adjacent to Sefton Park and the Mersey, Aigburth is one of Liverpool\'s most sought-after suburbs — premium private rental market with professional and family tenants.', propertyTypes:'Large Victorian semis, premium rentals, family homes', nearbyAreas:['Sefton Park','Grassendale','Allerton'], lat:53.3755, lng:-2.9397 },
  { slug:'allerton', name:'Allerton', postcode:'L18', region:'liverpool', borough:'Liverpool', tier:1, localContext:'One of Liverpool\'s most affluent suburbs — premium residential market with large detached and semi-detached properties in active private rental.', propertyTypes:'Large detached homes, premium semis, executive rentals', nearbyAreas:['Mossley Hill','Childwall','Woolton'], lat:53.3756, lng:-2.8980 },
  { slug:'mossley-hill', name:'Mossley Hill', postcode:'L18', region:'liverpool', borough:'Liverpool', tier:2, localContext:'A prestigious Liverpool suburb with large Victorian properties and tree-lined avenues — premium rental market popular with professionals.', propertyTypes:'Large Victorian houses, premium semis, professional rentals', nearbyAreas:['Allerton','Aigburth','Childwall'], lat:53.3858, lng:-2.9073 },
  { slug:'childwall', name:'Childwall', postcode:'L16', region:'liverpool', borough:'Liverpool', tier:2, localContext:'East Liverpool suburb popular with professional families — active private rental market with good schools driving consistent family tenant demand.', propertyTypes:'Interwar semis, detached family homes, professional rentals', nearbyAreas:['Allerton','Broadgreen','Wavertree'], lat:53.3985, lng:-2.9009 },
  { slug:'woolton', name:'Woolton', postcode:'L25', region:'liverpool', borough:'Liverpool', tier:2, localContext:'A village-like suburb famous as Paul McCartney\'s home area — premium residential market with affluent owner-occupiers and high-quality rental demand.', propertyTypes:'Large detached homes, premium semis, high-value rental properties', nearbyAreas:['Allerton','Hunts Cross','Gateacre'], lat:53.3691, lng:-2.8718 },
  { slug:'west-derby', name:'West Derby', postcode:'L12', region:'liverpool', borough:'Liverpool', tier:2, localContext:'An established east Liverpool suburb with a stable private rental market — popular with families in large interwar semis.', propertyTypes:'Interwar semis, detached family homes, family rentals', nearbyAreas:['Norris Green','Old Swan','Tuebrook'], lat:53.4243, lng:-2.9143 },
  { slug:'norris-green', name:'Norris Green', postcode:'L11', region:'liverpool', borough:'Liverpool', tier:2, localContext:'A large north-east Liverpool estate with significant social and private rental activity — consistent demand for affordable professional cleaning services.', propertyTypes:'Estate housing, council and private lets, family homes', nearbyAreas:['West Derby','Croxteth','Fazakerley'], lat:53.4397, lng:-2.9260 },
  { slug:'croxteth', name:'Croxteth', postcode:'L11', region:'liverpool', borough:'Liverpool', tier:2, localContext:'North Liverpool suburb with a large social and private rental market close to Croxteth Hall — consistent cleaning demand.', propertyTypes:'Estate housing, private lets, family homes', nearbyAreas:['Norris Green','Gillmoss','West Derby'], lat:53.4451, lng:-2.9030 },
  { slug:'fazakerley', name:'Fazakerley', postcode:'L9', region:'liverpool', borough:'Liverpool', tier:2, localContext:'Home to Aintree Racecourse and Liverpool University Hospital — a large north Liverpool residential area with active private rental.', propertyTypes:'Interwar semis, terraces, private lets, family rentals', nearbyAreas:['Walton','Aintree','Norris Green'], lat:53.4571, lng:-2.9471 },
  { slug:'aintree', name:'Aintree', postcode:'L10', region:'liverpool', borough:'Liverpool', tier:2, localContext:'Famous for the Grand National, Aintree has a stable residential area with active family rental market — especially strong around race day periods for Airbnb.', propertyTypes:'Semis, family rentals, race-day Airbnb properties', nearbyAreas:['Fazakerley','Walton','Maghull'], lat:53.4662, lng:-2.9618 },
  { slug:'old-swan', name:'Old Swan', postcode:'L13', region:'liverpool', borough:'Liverpool', tier:2, localContext:'A central Liverpool suburb and transport hub — busy private rental market with consistent EOT demand throughout the year.', propertyTypes:'Victorian terraces, interwar semis, private lets', nearbyAreas:['Wavertree','Kensington','West Derby'], lat:53.4096, lng:-2.9197 },
  { slug:'broadgreen', name:'Broadgreen', postcode:'L14', region:'liverpool', borough:'Liverpool', tier:2, localContext:'East Liverpool suburb home to Broadgreen Hospital — consistent demand for professional letting and medical staff accommodation cleaning.', propertyTypes:'Semis, family rentals, professional lets', nearbyAreas:['Childwall','Old Swan','Knotty Ash'], lat:53.4040, lng:-2.9071 },
  { slug:'tuebrook', name:'Tuebrook', postcode:'L13', region:'liverpool', borough:'Liverpool', tier:2, localContext:'Between the city centre and the eastern suburbs — a dense Victorian residential area with active private rental market popular with students and young professionals.', propertyTypes:'Victorian terraces, HMOs, student and professional lets', nearbyAreas:['Old Swan','Kensington','West Derby'], lat:53.4169, lng:-2.9351 },
  { slug:'speke', name:'Speke', postcode:'L24', region:'liverpool', borough:'Liverpool', tier:2, localContext:'Home to Liverpool John Lennon Airport and major distribution centres — consistent rental demand from airport workers and logistics employees.', propertyTypes:'Estate housing, family rentals, affordable private lets', nearbyAreas:['Halewood','Hunts Cross','Garston'], lat:53.3527, lng:-2.8674 },
  { slug:'garston', name:'Garston', postcode:'L19', region:'liverpool', borough:'Liverpool', tier:2, localContext:'A south Liverpool suburb on the Mersey — active private rental market with consistent EOT demand.', propertyTypes:'Victorian terraces, interwar semis, family rentals', nearbyAreas:['Aigburth','Speke','Hunts Cross'], lat:53.3605, lng:-2.9241 },
  { slug:'hunts-cross', name:'Hunts Cross', postcode:'L25', region:'liverpool', borough:'Liverpool', tier:2, localContext:'South Liverpool suburb at the end of the Merseyrail line — popular with professional commuters in private rentals.', propertyTypes:'Semis, family homes, professional rentals', nearbyAreas:['Woolton','Garston','Speke'], lat:53.3682, lng:-2.9004 },
  { slug:'halewood', name:'Halewood', postcode:'L26', region:'liverpool', borough:'Knowsley', tier:2, localContext:'South of Liverpool close to Jaguar Land Rover\'s Halewood plant — consistent demand from automotive workers for professional cleaning.', propertyTypes:'New build estates, family homes, worker rentals', nearbyAreas:['Speke','Huyton','Whiston'], lat:53.3645, lng:-2.8388 },
  { slug:'huyton', name:'Huyton', postcode:'L36', region:'liverpool', borough:'Knowsley', tier:2, localContext:'Knowsley\'s main town has a large private rental market — active EOT and deep cleaning demand throughout the year.', propertyTypes:'Estate housing, semis, family rentals, private lets', nearbyAreas:['Halewood','Prescot','Kirkby'], lat:53.4098, lng:-2.8515 },
  { slug:'kirkby', name:'Kirkby', postcode:'L32', region:'liverpool', borough:'Knowsley', tier:2, localContext:'One of Merseyside\'s largest towns with a significant private rental market — consistent demand for affordable professional cleaning across family homes.', propertyTypes:'Estate housing, family semis, council and private lets', nearbyAreas:['Aintree','Huyton','Maghull'], lat:53.4815, lng:-2.8964 },
  { slug:'prescot', name:'Prescot', postcode:'L34', region:'liverpool', borough:'Knowsley', tier:2, localContext:'A historic Knowsley town growing rapidly due to the Shakespeare North Playhouse development — active private rental market across its residential areas.', propertyTypes:'Victorian terraces, family semis, private lets', nearbyAreas:['Huyton','Whiston','St Helens'], lat:53.4275, lng:-2.7992 },
  { slug:'bootle', name:'Bootle', postcode:'L20', region:'liverpool', borough:'Sefton', tier:2, localContext:'North Liverpool/South Sefton — a large dense residential area with significant private rental market adjacent to the docks.', propertyTypes:'Victorian terraces, private lets, family rentals', nearbyAreas:['Kirkdale','Seaforth','Litherland'], lat:53.4444, lng:-3.0088 },
  { slug:'crosby', name:'Crosby', postcode:'L23', region:'liverpool', borough:'Sefton', tier:2, localContext:'A desirable north Liverpool/Sefton suburb close to Antony Gormley\'s Another Place — active private rental market of Victorian properties popular with professional families.', propertyTypes:'Victorian semis, family homes, professional rentals', nearbyAreas:['Waterloo','Formby','Bootle'], lat:53.4854, lng:-3.0357 },
  { slug:'formby', name:'Formby', postcode:'L37', region:'liverpool', borough:'Sefton', tier:2, localContext:'An aspirational coastal town north of Liverpool — one of Merseyside\'s most desirable addresses with premium properties and a strong cleaning market.', propertyTypes:'Large detached homes, premium semis, rural coastal properties', nearbyAreas:['Crosby','Southport','Maghull'], lat:53.5568, lng:-3.0694 },
  { slug:'maghull', name:'Maghull', postcode:'L31', region:'liverpool', borough:'Sefton', tier:2, localContext:'A large north Sefton town with active family rental market — consistent EOT and regular cleaning demand.', propertyTypes:'Semis, family homes, private rentals', nearbyAreas:['Aintree','Formby','Kirkby'], lat:53.5161, lng:-2.9348 },
  { slug:'waterloo-liverpool', name:'Waterloo', postcode:'L22', region:'liverpool', borough:'Sefton', tier:2, localContext:'Coastal suburb between Crosby and Bootle — popular with professionals in Victorian properties close to the Mersey and the beach.', propertyTypes:'Victorian semis, professional rentals, coastal properties', nearbyAreas:['Crosby','Bootle','Litherland'], lat:53.4710, lng:-3.0290 },
  { slug:'southport', name:'Southport', postcode:'PR8', region:'liverpool', borough:'Sefton', tier:1, localContext:'A major seaside resort town with high Airbnb and holiday let density — one of the highest short-let cleaning turnovers in the North West outside of the city centres.', propertyTypes:'Holiday lets, Airbnb properties, Victorian hotels converted to flats, family homes', nearbyAreas:['Formby','Maghull','Ormskirk'], lat:53.6452, lng:-3.0056 },
  { slug:'st-helens', name:'St Helens', postcode:'WA10', region:'liverpool', borough:'St Helens', tier:1, localContext:'A large industrial and residential town between Liverpool and Manchester — significant private rental market with consistent EOT and deep cleaning demand year-round.', propertyTypes:'Victorian terraces, interwar semis, family rentals, HMOs', nearbyAreas:['Prescot','Haydock','Earlestown'], lat:53.4519, lng:-2.7352 },
  { slug:'haydock', name:'Haydock', postcode:'WA11', region:'liverpool', borough:'St Helens', tier:2, localContext:'Close to Haydock Park Racecourse and the M6 — a residential area with active private rental market popular with commuters.', propertyTypes:'Family semis, detached homes, private rentals', nearbyAreas:['St Helens','Newton-le-Willows','Wigan'], lat:53.4767, lng:-2.6729 },
  { slug:'newton-le-willows', name:'Newton-le-Willows', postcode:'WA12', region:'liverpool', borough:'St Helens', tier:2, localContext:'Between St Helens and Warrington — a commuter town with active private rental market benefiting from excellent motorway access.', propertyTypes:'Semis, family homes, commuter rentals', nearbyAreas:['St Helens','Haydock','Warrington'], lat:53.4534, lng:-2.6365 },
  { slug:'birkenhead', name:'Birkenhead', postcode:'CH41', region:'liverpool', borough:'Wirral', tier:1, localContext:'Merseyside\'s second city across the Mersey — large private rental market, significant regeneration activity, and consistent professional cleaning demand.', propertyTypes:'Victorian terraces, town centre flats, HMOs, private lets', nearbyAreas:['Wallasey','Prenton','Bebington'], lat:53.3930, lng:-3.0195 },
  { slug:'wallasey', name:'Wallasey', postcode:'CH44', region:'liverpool', borough:'Wirral', tier:2, localContext:'North Wirral peninsula town with a large residential rental market and stunning coastal views — active EOT cleaning demand.', propertyTypes:'Victorian terraces, interwar semis, coastal private lets', nearbyAreas:['Birkenhead','New Brighton','Liscard'], lat:53.4163, lng:-3.0503 },
  { slug:'bebington', name:'Bebington', postcode:'CH63', region:'liverpool', borough:'Wirral', tier:2, localContext:'South Wirral suburb close to the Lever Brothers\' Port Sunlight heritage village — desirable residential area with premium rental market.', propertyTypes:'Edwardian semis, detached family homes, premium rentals', nearbyAreas:['Birkenhead','Bromborough','Heswall'], lat:53.3575, lng:-3.0067 },
  { slug:'heswall', name:'Heswall', postcode:'CH60', region:'liverpool', borough:'Wirral', tier:2, localContext:'One of Wirral\'s most desirable addresses with views across the Dee Estuary — affluent residential market with premium cleaning demand.', propertyTypes:'Large detached homes, premium properties, executive rentals', nearbyAreas:['West Kirby','Bebington','Neston'], lat:53.3289, lng:-3.1003 },
  { slug:'west-kirby', name:'West Kirby', postcode:'CH48', region:'liverpool', borough:'Wirral', tier:2, localContext:'A premium coastal town on the Dee Estuary — popular with professionals and retired affluent residents, with a strong cleaning market.', propertyTypes:'Coastal properties, premium detached homes, executive rentals', nearbyAreas:['Hoylake','Heswall','Meols'], lat:53.3727, lng:-3.1810 },

  // ═══════════════════════════════════════════════════════
  // CARLISLE & CUMBRIA
  // ═══════════════════════════════════════════════════════

  { slug:'carlisle-city-centre', name:'Carlisle City Centre', postcode:'CA1', region:'carlisle', borough:'Carlisle', tier:1, localContext:'The historic capital of Cumbria, Carlisle city centre has a growing apartment rental market driven by University of Cumbria students, Cumberland Infirmary NHS staff, and young professionals — consistent EOT and deep cleaning demand year-round.', propertyTypes:'City centre apartments, converted Victorian townhouses, student accommodation, professional lets', nearbyAreas:['Stanwix','Botcherby','Harraby','Caldewgate'], lat:54.8951, lng:-2.9382 },
  { slug:'stanwix', name:'Stanwix', postcode:'CA3', region:'carlisle', borough:'Carlisle', tier:2, localContext:'Carlisle\'s most desirable residential suburb on the north bank of the Eden — Victorian and Edwardian houses popular with professional and family tenants expecting high cleaning standards at checkout.', propertyTypes:'Victorian semis, Edwardian detached homes, professional and family private rentals', nearbyAreas:['Carlisle City Centre','Etterby','Kingstown'], lat:54.9021, lng:-2.9429 },
  { slug:'botcherby', name:'Botcherby', postcode:'CA1', region:'carlisle', borough:'Carlisle', tier:2, localContext:'East Carlisle residential neighbourhood with a stable private rental market of interwar and postwar semis — consistent EOT cleaning demand throughout the year.', propertyTypes:'Interwar semis, postwar estate housing, private family lets', nearbyAreas:['Carlisle City Centre','Harraby','Upperby'], lat:54.8856, lng:-2.9175 },
  { slug:'scotby', name:'Scotby', postcode:'CA4', region:'carlisle', borough:'Carlisle', tier:2, localContext:'A picturesque village just east of Carlisle popular with professional families commuting to the city — executive and high-quality private rentals requiring premium cleaning standards.', propertyTypes:'Detached village properties, executive homes, premium family rentals', nearbyAreas:['Carlisle City Centre','Brampton','Wetheral'], lat:54.8867, lng:-2.8932 },
  { slug:'dalston', name:'Dalston', postcode:'CA5', region:'carlisle', borough:'Carlisle', tier:2, localContext:'A traditional Cumbrian village south-west of Carlisle popular with rural property buyers and renters — consistent demand for professional deep cleaning between tenancies.', propertyTypes:'Detached rural properties, village semis, character family rentals', nearbyAreas:['Carlisle City Centre','Wigton','Thursby'], lat:54.8531, lng:-2.9847 },
  { slug:'wigton', name:'Wigton', postcode:'CA7', region:'carlisle', borough:'Carlisle', tier:1, localContext:'A historic market town 12 miles south-west of Carlisle — the main service centre for west Cumbria with a stable residential rental market and growing demand for professional cleaning services.', propertyTypes:'Victorian terraces, market town semis, family rentals', nearbyAreas:['Carlisle City Centre','Dalston','Aspatria'], lat:54.8272, lng:-3.1598 },
  { slug:'brampton', name:'Brampton', postcode:'CA8', region:'carlisle', borough:'Carlisle', tier:2, localContext:'A charming market town 9 miles east of Carlisle on the edge of Hadrian\'s Wall country — holiday lets and permanent rentals create consistent cleaning demand, particularly around peak tourist seasons.', propertyTypes:'Stone cottages, holiday lets, market town semis, rural rentals', nearbyAreas:['Carlisle City Centre','Scotby','Haltwhistle'], lat:54.9292, lng:-2.7262 },
  { slug:'longtown', name:'Longtown', postcode:'CA6', region:'carlisle', borough:'Carlisle', tier:2, localContext:'A border town 9 miles north of Carlisle known for its livestock market — modest residential area with local professional and family rental demand close to the Scottish border.', propertyTypes:'Victorian terraces, family semis, private lets, border-town properties', nearbyAreas:['Carlisle City Centre','Gretna','Canonbie'], lat:54.9742, lng:-2.9694 },
  { slug:'penrith', name:'Penrith', postcode:'CA11', region:'carlisle', borough:'Eden', tier:1, localContext:'The gateway to the Lake District and Eden Valley — Penrith has a buoyant rental market driven by tourism, the M6 corridor, and its growing professional base close to the Lakes.', propertyTypes:'Stone townhouses, family semis, rural cottages, holiday lets', nearbyAreas:['Carlisle City Centre','Appleby-in-Westmorland','Keswick'], lat:54.6640, lng:-2.7567 },
  { slug:'appleby-in-westmorland', name:'Appleby-in-Westmorland', postcode:'CA16', region:'carlisle', borough:'Eden', tier:3, localContext:'A historic Eden Valley market town famous for the annual Horse Fair — holiday lets and permanent residences in traditional stone properties create specialist cleaning demand throughout the year.', propertyTypes:'Stone cottages, holiday lets, traditional townhouses, rural Eden Valley properties', nearbyAreas:['Penrith','Kirkby Stephen','Carlisle City Centre'], lat:54.5786, lng:-2.4940 },
]

// ─────────────────────────────────────────────────────────────────
// REGION METADATA for UI and SEO
// ─────────────────────────────────────────────────────────────────

export const REGIONS = {
  manchester: {
    name: 'Greater Manchester',
    tagline: 'All 10 Boroughs Covered',
    description: 'From Manchester City Centre to Bolton, Wigan to Stockport — we cover every one of Greater Manchester\'s 10 metropolitan boroughs.',
    boroughs: ['Manchester','Salford','Trafford','Stockport','Tameside','Wigan','Bolton','Bury','Oldham','Rochdale'],
    postcodes: ['M1','M2','M3','M4','M5','M6','M7','M8','M9','M11','M12','M13','M14','M15','M16','M17','M18','M19','M20','M21','M22','M23','M24','M25','M26','M27','M28','M29','M30','M31','M32','M33','M34','M35','M38','M40','M41','M43','M44','M45','M46','M50','BL1','BL2','BL3','BL4','BL5','BL6','BL7','BL8','BL9','OL1','OL6','OL9','OL10','OL11','SK1','SK3','SK4','SK5','SK6','SK7','SK8','SK14','SK15','WA14','WA15','WN1','WN7'],
  },
  crewe: {
    name: 'Crewe & Cheshire East',
    tagline: 'Hyper-Local Cheshire Coverage',
    description: 'From Crewe town centre to Alderley Edge, Nantwich to Macclesfield — deep coverage across every ward and village in Cheshire East.',
    boroughs: ['Cheshire East','Newcastle-under-Lyme'],
    postcodes: ['CW1','CW2','CW3','CW4','CW5','CW6','CW7','CW10','CW11','CW12','SK9','SK10','SK11','SK12','WA16','ST7'],
  },
  stoke: {
    name: 'Stoke-on-Trent & Staffordshire',
    tagline: 'Serving the Potteries and Beyond',
    description: 'From Hanley to Longton, Newcastle-under-Lyme to Stafford — covering all six towns of Stoke-on-Trent and North Staffordshire.',
    boroughs: ['Stoke-on-Trent','Newcastle-under-Lyme','Stafford'],
    postcodes: ['ST1','ST2','ST3','ST4','ST5','ST6','ST7','ST15','ST16'],
  },
  liverpool: {
    name: 'Liverpool & Merseyside',
    tagline: 'City, Suburbs & Coastal Communities',
    description: 'From Liverpool City Centre to Southport, Birkenhead to Huyton — comprehensive coverage across all five Merseyside boroughs.',
    boroughs: ['Liverpool','Knowsley','Sefton','St Helens','Wirral'],
    postcodes: ['L1','L2','L3','L4','L5','L6','L7','L8','L9','L10','L11','L12','L13','L14','L15','L16','L17','L18','L19','L20','L21','L22','L23','L24','L25','L26','L27','L31','L32','L33','L34','L36','L37','WA10','WA11','WA12','CH41','CH44','CH48','CH60','CH63','PR8'],
  },
  carlisle: {
    name: 'Carlisle & Cumbria',
    tagline: 'Capital of Cumbria & the Eden Valley',
    description: 'From Carlisle City Centre to Penrith, Wigton to Brampton — professional cleaning across Carlisle, Eden, and the surrounding Cumbrian countryside.',
    boroughs: ['Carlisle','Eden'],
    postcodes: ['CA1','CA2','CA3','CA4','CA5','CA6','CA7','CA8','CA11','CA16'],
  },
}

// Helper — get all locations for a region
export const getLocationsByRegion = (region: Region) =>
  LOCATIONS_EXPANDED.filter(l => l.region === region)

// Helper — get all locations for a borough
export const getLocationsByBorough = (borough: string) =>
  LOCATIONS_EXPANDED.filter(l => l.borough === borough)

// Total count
export const TOTAL_LOCATIONS = LOCATIONS_EXPANDED.length
export const TOTAL_PAGES = LOCATIONS_EXPANDED.length * 8  // 8 services
