// lib/seo-data.ts
// THE ENGINE — all 8 services × 60 locations = 480 unique indexable pages
// Each location has hyper-local context used in page body copy

export interface ServiceData {
  slug: string
  name: string
  shortName: string
  tagline: string
  metaDescription: string
  h1Template: string        // {location} replaced dynamically
  intro: string             // {location}, {postcode} replaced
  included: string[]
  addons: string[]
  prices: { label: string; price: string }[]
  faqs: { q: string; a: string }[]
  cta: string
  schema: string            // schema.org @type for this service
}

export interface LocationData {
  slug: string
  name: string
  postcode: string
  region: 'manchester' | 'crewe' | 'liverpool' | 'stoke' | 'carlisle'
  tier: 1 | 2 | 3
  localContext: string      // 1–2 sentences of genuine local flavour for body copy
  propertyTypes: string     // e.g. "Victorian terraces, modern flats"
  nearbyAreas: string[]     // for internal linking
  lat: number
  lng: number
}

// ─────────────────────────────────────────────
// 8 SERVICES
// ─────────────────────────────────────────────

export const SERVICES: ServiceData[] = [
  {
    slug: 'end-of-tenancy-cleaning',
    name: 'End of Tenancy Cleaning',
    shortName: 'End of Tenancy',
    tagline: 'Get your full deposit back — guaranteed.',
    metaDescription: 'Professional end of tenancy cleaning in {location} from £110. Letting agent approved standard. DBS-checked team, certificate of clean provided. Call 07767 759 013.',
    h1Template: 'End of Tenancy Cleaning in {location}',
    intro: 'Moving out of a property in {location}? Our end of tenancy cleaning service is fully approved to letting agent and inventory clerk standards. We clean every room to inspection level, provide a certificate of clean, and back it with our deposit-return guarantee. Our DBS-checked team covers {postcode} and the surrounding area — weekdays, weekends, and short notice available.',
    included: [
      'Full kitchen deep clean including oven, extractor, and hob',
      'Bathroom and en-suite scrubbed to inspection standard',
      'All floors vacuumed and mopped',
      'Skirting boards, door frames, and light switches wiped',
      'Inside all cupboards and drawers',
      'Limescale removed from tiles, taps, and shower screens',
      'Interior windows and window sills cleaned',
      'Certificate of clean provided on request',
    ],
    addons: ['Carpet extraction cleaning', 'Exterior windows', 'Garage or outbuilding', 'Garden tidying'],
    prices: [
      { label: 'Studio / 1-Bed', price: '£110' },
      { label: '2-Bed Property', price: '£155' },
      { label: '3-Bed Property', price: '£200' },
      { label: '4-Bed Property', price: '£260' },
      { label: '5-Bed Property', price: 'POA' },
    ],
    faqs: [
      { q: 'Do you guarantee the deposit back?', a: 'Yes. If your letting agent or landlord raises a cleaning issue we covered, we return and re-clean the relevant areas at no extra charge. Most clients get their full deposit returned after our clean.' },
      { q: 'How long does an end of tenancy clean take?', a: 'A 1-bed flat typically takes 3–4 hours. A 3-bed house takes 5–7 hours. We work until the property meets inspection standard, not until a timer runs out.' },
      { q: 'Do I need to be present during the clean?', a: 'No. Most clients arrange key collection via a lockbox or leave keys with us. We\'re fully insured and DBS-checked — your property is safe in our hands.' },
      { q: 'How much notice do you need for an end of tenancy clean?', a: 'We ask for at least 48 hours where possible, but we regularly take last-minute bookings. Call 07767 759 013 to check availability for your move-out date.' },
    ],
    cta: 'Book Your End of Tenancy Clean',
    schema: 'HouseCleaner',
  },
  {
    slug: 'deep-cleaning',
    name: 'Deep Cleaning',
    shortName: 'Deep Clean',
    tagline: 'Top to bottom. Every detail, every corner.',
    metaDescription: 'Professional deep cleaning in {location} from £75. One-off intensive clean covering every room, appliance, and surface. DBS-checked, fully insured. Call 07767 759 013.',
    h1Template: 'Deep Cleaning Service in {location}',
    intro: 'Our deep cleaning service in {location} goes far beyond a standard clean. Every surface, appliance, and hidden corner is tackled by our trained team — ideal for a seasonal refresh, before moving in, after building work, or simply when your home needs a proper reset. We cover the full {postcode} area and can usually book within 3–5 days.',
    included: [
      'Kitchen: oven, hob, extractor, fridge, microwave deep cleaned',
      'Bathrooms and en-suites: limescale removal, grout scrubbing',
      'Skirting boards, door frames, light switches, and plug sockets wiped',
      'Inside all wardrobes, cupboards, and drawers',
      'All floors vacuumed and mopped, including under furniture',
      'Window sills, frames, and interior glass cleaned',
      'Cobweb removal throughout',
      'Balcony or patio swept if accessible',
    ],
    addons: ['Carpet extraction', 'Upholstery cleaning', 'Inside oven only', 'Garage included'],
    prices: [
      { label: 'Studio / 1-Bed', price: '£75' },
      { label: '2-Bed Property', price: '£100' },
      { label: '3-Bed Property', price: '£130' },
      { label: '4-Bed Property', price: '£170' },
    ],
    faqs: [
      { q: 'What is the difference between a regular clean and a deep clean?', a: 'A regular clean maintains your home week to week. A deep clean starts from scratch — inside appliances, behind furniture, inside cupboards, grout lines, limescale — areas a standard clean doesn\'t reach.' },
      { q: 'How often should I get a deep clean?', a: 'Most households book a deep clean every 3–6 months to complement regular maintenance cleaning. It\'s also common before hosting events, after illness, or after building work.' },
      { q: 'Do I need to prepare anything before the deep clean?', a: 'Just clear any personal items you\'d prefer we don\'t move, and ensure hot water and power are available. We bring all our own professional cleaning supplies.' },
      { q: 'Can I get a same-week deep clean?', a: 'In most cases yes. We aim to accommodate bookings within 3–5 days. Call 07767 759 013 or WhatsApp us for the quickest availability.' },
    ],
    cta: 'Book Your Deep Clean',
    schema: 'HouseCleaner',
  },
  {
    slug: 'regular-house-cleaning',
    name: 'Regular Home Cleaning',
    shortName: 'Regular Clean',
    tagline: 'Your cleaner, every week. Same person, same standard.',
    metaDescription: 'Regular house cleaning in {location} from £35. Weekly, fortnightly, or monthly. Same DBS-checked cleaner every visit. No contracts. Call 07767 759 013.',
    h1Template: 'Regular House Cleaning in {location}',
    intro: 'Life is busy enough. Our regular cleaning service gives {location} homes a consistent, professional clean without the hassle — weekly, fortnightly, or monthly, always from the same trusted cleaner. No contracts, no lock-in, and always the same face at your door. We serve {postcode} and the surrounding area.',
    included: [
      'Kitchen: worktops, hob, appliance exteriors, sink, cupboard fronts',
      'Bathrooms: toilet, sink, bath/shower, mirrors, tiles',
      'Dusting of all surfaces and furniture throughout',
      'Vacuuming all carpets and upholstered furniture',
      'Mopping all hard floors',
      'Bins emptied and relined',
      'Beds made and changed (linen provided by client)',
    ],
    addons: ['Inside fridge clean', 'Inside oven clean', 'Interior windows', 'Laundry and ironing'],
    prices: [
      { label: '1-Bed (weekly)', price: '£35' },
      { label: '2-Bed (weekly)', price: '£50' },
      { label: '3-Bed (weekly)', price: '£65' },
      { label: '4-Bed (weekly)', price: '£80' },
    ],
    faqs: [
      { q: 'Will I always have the same cleaner?', a: 'Yes. We match you with one of our team and aim to send the same person every visit. In cases of illness or holiday, we will always give you advance notice and offer a replacement of equal standard.' },
      { q: 'Do I need to be home during the clean?', a: 'Not at all. Most regular clients provide a key or code. We\'re DBS-checked, fully insured, and trusted to clean homes unsupervised across {location} and the surrounding area.' },
      { q: 'Is there a minimum contract?', a: 'No. We operate on a no-contract basis. You can pause, reduce frequency, or cancel at any time with 48 hours notice. We\'d rather earn your business every visit than lock you in.' },
      { q: 'Do you bring cleaning supplies?', a: 'Yes. We bring all professional-grade products. If you have allergies or prefer eco-friendly products, just let us know when you book — we carry non-toxic alternatives at no extra charge.' },
    ],
    cta: 'Set Up Your Regular Clean',
    schema: 'HouseCleaner',
  },
  {
    slug: 'move-in-move-out-cleaning',
    name: 'Move In / Move Out Cleaning',
    shortName: 'Move In / Move Out',
    tagline: 'Fresh start in your new home. Perfect finish when you leave.',
    metaDescription: 'Move in and move out cleaning in {location} from £110. Clean your new home before you unpack or leave your old one spotless. DBS-checked, fully insured. 07767 759 013.',
    h1Template: 'Move In & Move Out Cleaning in {location}',
    intro: 'Moving home in {location}? Whether you\'re arriving at a new property and want it properly cleaned before you unpack, or you\'re leaving and need to hand it back in perfect condition, our move in/move out service covers you completely. We cover {postcode} and operate 7 days a week to fit around completion and moving dates.',
    included: [
      'Full kitchen clean including all appliances inside and out',
      'Bathroom and toilet cleaned and sanitised',
      'All rooms dusted, vacuumed, and mopped',
      'Inside all built-in cupboards and wardrobes',
      'Skirting boards, doors, and frames wiped',
      'Interior windows cleaned',
      'Any marks or scuffs removed from walls where possible',
      'Garden or patio swept if required',
    ],
    addons: ['Carpet cleaning', 'External window cleaning', 'Garage clean', 'Garden tidy'],
    prices: [
      { label: 'Studio / 1-Bed', price: '£110' },
      { label: '2-Bed Property', price: '£150' },
      { label: '3-Bed Property', price: '£195' },
      { label: '4-Bed Property', price: '£250' },
    ],
    faqs: [
      { q: 'What is the difference between move in and end of tenancy cleaning?', a: 'End of tenancy cleaning is for renters and must meet letting agent standards. Move in cleaning is typically for buyers or renters who want their new home cleaned to their own personal standard before they move in — often more detailed around specific areas they care about most.' },
      { q: 'Can you clean the property before our furniture arrives?', a: 'Yes — in fact this is the ideal scenario. An empty property allows us to clean more thoroughly, particularly floors, skirting boards, and built-in storage.' },
      { q: 'Can you accommodate completion day timings?', a: 'Yes. We know completion and handover times can shift. We offer flexible morning or afternoon slots and will do our best to work around your estate agent or removal company schedule.' },
      { q: 'Do you cover properties across {location}?', a: 'Yes. We operate across {postcode} and all surrounding areas. Contact us with your property address and we\'ll confirm availability and pricing.' },
    ],
    cta: 'Book Your Move Clean',
    schema: 'HouseCleaner',
  },
  {
    slug: 'carpet-cleaning',
    name: 'Carpet & Upholstery Cleaning',
    shortName: 'Carpet Cleaning',
    tagline: 'Deep extraction. Fresh results. Per room or whole house.',
    metaDescription: 'Professional carpet cleaning in {location} from £25/room. Hot water extraction removes deep stains, odours, and allergens. DBS-checked team. Call 07767 759 013.',
    h1Template: 'Carpet & Upholstery Cleaning in {location}',
    intro: 'Our carpet cleaning service uses professional hot water extraction to remove deep-set dirt, stains, pet odours, and allergens from carpets and upholstery across {location}. Unlike surface-only methods, hot water extraction cleans deep into the pile, leaving carpets genuinely fresh — not just damp. We cover {postcode} and the surrounding area, with results visible within hours of drying.',
    included: [
      'Pre-inspection and stain pre-treatment',
      'Professional hot water extraction (not dry cleaning)',
      'Deodorising treatment included',
      'Pet odour and hair treatment available',
      'Furniture moved where safe to do so',
      'Fast-dry technique — walkable in 2–4 hours',
    ],
    addons: ['Upholstery (2-seat sofa)', 'Stair runners', 'Mattress cleaning', 'Area rug cleaning'],
    prices: [
      { label: 'Per bedroom', price: '£25' },
      { label: 'Stairs', price: '£20' },
      { label: 'Large living room', price: '£30' },
      { label: '3-bed full house', price: '£120' },
      { label: '2-seat sofa (upholstery)', price: '£55' },
    ],
    faqs: [
      { q: 'How long do carpets take to dry after cleaning?', a: 'With our fast-dry extraction method, most carpets are walkable within 2–4 hours. Full drying typically takes 6–8 hours depending on the thickness of the carpet and ventilation in the room.' },
      { q: 'Can you remove pet stains and odours?', a: 'Yes. We use specialist enzyme-based treatments for pet urine, fur, and odours that break down the source of the smell rather than masking it. Heavily saturated areas may need more than one treatment for full results.' },
      { q: 'Are your products safe for children and pets?', a: 'Yes. We use products that are safe once dry. We recommend keeping children and pets off the carpet until it is fully dry, usually 4–6 hours after cleaning.' },
      { q: 'Do you clean upholstery and sofas as well as carpets?', a: 'Yes. We clean sofas, chairs, headboards, and other fabric upholstery using the same hot water extraction method. Prices start from £55 for a 2-seat sofa.' },
    ],
    cta: 'Book Carpet Cleaning',
    schema: 'HouseCleaner',
  },
  {
    slug: 'office-commercial-cleaning',
    name: 'Office & Commercial Cleaning',
    shortName: 'Office Cleaning',
    tagline: 'Reliable contract cleaning built around your business hours.',
    metaDescription: 'Office and commercial cleaning in {location} from £65/visit. Daily, weekly, or out-of-hours. DBS-checked staff, £5M insured. Contract or flexible. Call 07767 759 013.',
    h1Template: 'Office & Commercial Cleaning in {location}',
    intro: 'A clean workplace isn\'t just presentable — it improves staff wellbeing, reduces sick days, and makes the right impression on clients. thefamgroup provides reliable office and commercial cleaning for businesses across {location}, from small offices to larger commercial spaces. We work around your hours — early mornings, evenings, weekends — and provide fully vetted, insured operatives every visit. We cover {postcode} and the surrounding commercial areas.',
    included: [
      'All workstations, desks, and office equipment wiped and sanitised',
      'Kitchen and breakout area fully cleaned',
      'All toilets and washrooms sanitised',
      'Reception and common areas vacuumed and mopped',
      'Bins emptied and relined throughout',
      'Glass partitions and entry doors cleaned',
      'Door handles and high-touch surfaces disinfected',
    ],
    addons: ['Deep office clean (quarterly)', 'Carpet extraction', 'External window cleaning', 'Washroom supplies replenishment'],
    prices: [
      { label: 'Small office (up to 10 desks)', price: '£65/visit' },
      { label: 'Medium office (10–30 desks)', price: '£95/visit' },
      { label: 'Large office (30+ desks)', price: '£140/visit' },
      { label: 'Retail / showroom', price: '£85/visit' },
    ],
    faqs: [
      { q: 'Do you offer out-of-hours office cleaning?', a: 'Yes. Most of our commercial clients prefer cleaning outside business hours — before 8am or after 6pm. We accommodate early morning, evening, and weekend slots across {location}.' },
      { q: 'Are your staff DBS-checked for office access?', a: 'Yes. All thefamgroup operatives are DBS-checked, reference-verified, and carry public liability insurance. We understand the sensitivity of unsupervised access to business premises.' },
      { q: 'Do you offer flexible contracts or is there a minimum term?', a: 'Both options are available. We offer rolling monthly agreements with no lock-in, or discounted longer-term contracts if you prefer commitment in exchange for a lower rate.' },
      { q: 'Can you provide a cleaning schedule and log?', a: 'Yes. We provide a job completion log for every visit. For larger contracts, we also offer a monthly report and dedicated account manager contact.' },
    ],
    cta: 'Request a Commercial Quote',
    schema: 'LocalBusiness',
  },
  {
    slug: 'post-construction-cleaning',
    name: 'Post-Construction & Builders Clean',
    shortName: 'Builders Clean',
    tagline: 'Remove the dust. Reveal the finish.',
    metaDescription: 'Post-construction and builders clean in {location} from £180. Remove plaster dust, paint marks, and debris after building work. DBS-checked, fully insured. Call 07767 759 013.',
    h1Template: 'Post-Construction Cleaning in {location}',
    intro: 'After building work, renovation, or refurbishment, your property needs a clean that goes beyond standard domestic cleaning. Our post-construction cleaning team in {location} removes plaster dust, paint splatter, adhesive residue, grout film, and building debris — leaving your property ready to move into or hand over. We cover {postcode} and work around your contractor\'s schedule.',
    included: [
      'Fine plaster dust removal from all surfaces and crevices',
      'Paint marks and splatter removed from glass, sills, and floors',
      'Adhesive residue and grout haze removed',
      'All rooms vacuumed (HEPA-filter equipment for fine dust)',
      'Hard floors scrubbed and polished',
      'Sanitaryware and kitchen units cleaned and polished',
      'All windows cleaned inside and out (ground floor)',
      'Removal of packaging, off-cuts, and builder debris (bagged)',
    ],
    addons: ['External window cleaning (upper floors)', 'Carpet protection removal and vacuuming', 'Deep oven clean for new kitchens', 'Handover sparkle clean on completion day'],
    prices: [
      { label: '1-Bed / flat', price: '£150' },
      { label: '2-Bed property', price: '£200' },
      { label: '3-Bed property', price: '£280' },
      { label: 'Commercial (per sq ft)', price: 'POA' },
    ],
    faqs: [
      { q: 'When should we schedule the builders clean?', a: 'Ideally after all trades have finished and before any furniture is installed. A sparkle clean (lighter second pass) is then done just before handover or move-in day.' },
      { q: 'What equipment do you use for construction dust?', a: 'We use HEPA-filter vacuum equipment rated for fine particles. Standard domestic vacuums recirculate fine plaster dust into the air — ours capture it.' },
      { q: 'Can you work around contractors still on site?', a: 'Yes. We often do a first-fix clean while other trades are completing. We co-ordinate with your site manager and are experienced in working safely alongside other contractors.' },
      { q: 'Do you take away building waste?', a: 'We bag and remove small amounts of debris included in the standard service. For larger quantities of rubble or materials, a skip is more appropriate. We can advise on this when we quote.' },
    ],
    cta: 'Get a Post-Build Clean Quote',
    schema: 'LocalBusiness',
  },
  {
    slug: 'airbnb-holiday-let-cleaning',
    name: 'Airbnb & Holiday Let Cleaning',
    shortName: 'Airbnb Clean',
    tagline: '5-star standards. Fast turnaround. Every single time.',
    metaDescription: 'Airbnb and holiday let cleaning in {location} from £75. Fast turnaround between guests, linen change, restock, and inspection-standard finish. Call 07767 759 013.',
    h1Template: 'Airbnb & Holiday Let Cleaning in {location}',
    intro: 'Maintaining 5-star guest reviews depends on a consistently immaculate property between every booking. Our Airbnb and holiday let cleaning service in {location} is built around fast turnarounds, reliable scheduling, and an inspection-standard finish every time — regardless of what the previous guests left behind. We cover {postcode} with flexible same-day availability between checkouts and check-ins.',
    included: [
      'Full property cleaned and reset to hotel standard',
      'All beds stripped, fresh linen fitted (linen provided by owner)',
      'Bathrooms sanitised and restocked with supplies',
      'Kitchen wiped down, appliances cleaned, dishes washed',
      'All bins emptied and relined',
      'Guest welcome items arranged as directed',
      'Damage and inventory check reported to owner',
      'Photo confirmation sent on completion',
    ],
    addons: ['Linen laundry and press', 'Restock shopping (supplies provided by owner)', 'Deep clean between long stays', 'Window cleaning'],
    prices: [
      { label: 'Studio / 1-Bed', price: '£75' },
      { label: '2-Bed property', price: '£100' },
      { label: '3-Bed property', price: '£135' },
      { label: '4-Bed / large', price: '£170' },
    ],
    faqs: [
      { q: 'Can you handle same-day turnarounds between guests?', a: 'Yes — this is our speciality. We work to your check-out and check-in times and are set up to complete fast, thorough turnarounds even on the same day.' },
      { q: 'What happens if a guest leaves the property in poor condition?', a: 'We photograph the condition on arrival and on completion and notify you immediately. Any significant extra cleaning required beyond the standard service is quoted before we proceed.' },
      { q: 'Can you manage the cleaning schedule automatically?', a: 'Yes. Share your booking calendar with us (Airbnb, VRBO, or direct) and we\'ll schedule and confirm each clean automatically without you needing to contact us for each booking.' },
      { q: 'Do you cover multiple Airbnb properties?', a: 'Yes. We manage multi-property portfolios for several hosts across {location}. We offer volume pricing for hosts with two or more properties.' },
    ],
    cta: 'Set Up Airbnb Cleaning',
    schema: 'HouseCleaner',
  },
]

// ─────────────────────────────────────────────
// 60 LOCATIONS
// ─────────────────────────────────────────────

export const LOCATIONS: LocationData[] = [

  // ── MANCHESTER TIER 1 ──────────────────────
  {
    slug: 'didsbury',
    name: 'Didsbury',
    postcode: 'M20',
    region: 'manchester',
    tier: 1,
    localContext: 'Didsbury is one of south Manchester\'s most sought-after areas, known for its tree-lined streets, independent cafes on Didsbury Village, and strong rental market. Period Victorian and Edwardian properties dominate, and the area sees very high end of tenancy demand given its large student and professional rental population.',
    propertyTypes: 'Victorian terraces, Edwardian semis, purpose-built flats, period conversions',
    nearbyAreas: ['withington', 'chorlton', 'levenshulme', 'burnage'],
    lat: 53.4108,
    lng: -2.2135,
  },
  {
    slug: 'chorlton',
    name: 'Chorlton',
    postcode: 'M21',
    region: 'manchester',
    tier: 1,
    localContext: 'Chorlton is a vibrant, bohemian suburb popular with young families, creatives, and professionals. With a high proportion of private rentals along roads like Manchester Road and Beech Road, it generates consistent demand for end of tenancy, deep clean, and regular home cleaning services.',
    propertyTypes: 'Victorian terraces, converted flats, 1930s semis',
    nearbyAreas: ['didsbury', 'whalley-range', 'withington', 'sale'],
    lat: 53.4415,
    lng: -2.2716,
  },
  {
    slug: 'salford',
    name: 'Salford',
    postcode: 'M5',
    region: 'manchester',
    tier: 1,
    localContext: 'Salford sits directly across from Manchester city centre and has undergone significant regeneration, particularly around Salford Quays and Ordsall. A large and diverse rental market — from riverside apartments to traditional terraces in Eccles and Pendleton — creates high demand for all types of cleaning services.',
    propertyTypes: 'Waterfront apartments, terraced houses, new-build developments',
    nearbyAreas: ['salford-quays', 'eccles', 'old-trafford', 'manchester-city-centre'],
    lat: 53.4878,
    lng: -2.2901,
  },
  {
    slug: 'withington',
    name: 'Withington',
    postcode: 'M20',
    region: 'manchester',
    tier: 1,
    localContext: 'Withington borders Didsbury and Fallowfield and is home to a mix of students, young professionals, and long-term residents. High rental turnover near the University of Manchester creates consistent end of tenancy and deep clean demand throughout the year.',
    propertyTypes: 'Victorian terraces, converted student flats, semis',
    nearbyAreas: ['didsbury', 'fallowfield', 'levenshulme', 'northenden'],
    lat: 53.4248,
    lng: -2.2277,
  },
  {
    slug: 'fallowfield',
    name: 'Fallowfield',
    postcode: 'M14',
    region: 'manchester',
    tier: 1,
    localContext: 'Fallowfield is the heart of Manchester\'s student rental market, with thousands of shared houses in the streets around Wilmslow Road. High annual turnover at the end of academic tenancies — typically May to July — creates the highest concentration of end of tenancy cleaning demand in South Manchester.',
    propertyTypes: 'Shared houses, HMOs, converted Victorian terraces',
    nearbyAreas: ['rusholme', 'withington', 'levenshulme', 'moss-side'],
    lat: 53.4348,
    lng: -2.2189,
  },
  {
    slug: 'levenshulme',
    name: 'Levenshulme',
    postcode: 'M19',
    region: 'manchester',
    tier: 1,
    localContext: 'Levenshulme has transformed into one of South Manchester\'s most dynamic neighbourhoods, with a growing first-time buyer and renter market centred around the Levenshulme Train Station area and its weekend market. Renovation activity is high, driving demand for post-construction and deep cleaning.',
    propertyTypes: 'Victorian terraces, period conversions, new-build houses',
    nearbyAreas: ['heaton-moor', 'burnage', 'didsbury', 'longsight'],
    lat: 53.4398,
    lng: -2.1869,
  },
  {
    slug: 'whalley-range',
    name: 'Whalley Range',
    postcode: 'M16',
    region: 'manchester',
    tier: 1,
    localContext: 'Whalley Range is a leafy, eclectic residential area with a strong community identity and predominantly period housing stock. Its mix of family homes and private rented properties generates steady demand for regular and deep cleaning services throughout the year.',
    propertyTypes: 'Victorian and Edwardian semis, large terraces, purpose-built flats',
    nearbyAreas: ['chorlton', 'moss-side', 'old-trafford', 'stretford'],
    lat: 53.4523,
    lng: -2.2539,
  },
  {
    slug: 'rusholme',
    name: 'Rusholme',
    postcode: 'M14',
    region: 'manchester',
    tier: 1,
    localContext: 'Rusholme, famous for its Curry Mile on Wilmslow Road, has a high-density rental market catering primarily to university students and young professionals. End of tenancy and one-off deep cleaning are the dominant service demands in this area.',
    propertyTypes: 'Shared houses, purpose-built student flats, Victorian terraces',
    nearbyAreas: ['fallowfield', 'hulme', 'longsight', 'moss-side'],
    lat: 53.4449,
    lng: -2.2095,
  },
  {
    slug: 'hulme',
    name: 'Hulme',
    postcode: 'M15',
    region: 'manchester',
    tier: 1,
    localContext: 'Hulme sits adjacent to Manchester city centre and Oxford Road and is home to a young professional and student population in a mix of new-build apartments and older housing association properties. Proximity to the universities drives high end of tenancy demand.',
    propertyTypes: 'Modern apartments, new-build flats, social housing blocks',
    nearbyAreas: ['moss-side', 'manchester-city-centre', 'old-trafford', 'rusholme'],
    lat: 53.4624,
    lng: -2.2458,
  },
  {
    slug: 'old-trafford',
    name: 'Old Trafford',
    postcode: 'M16',
    region: 'manchester',
    tier: 1,
    localContext: 'Old Trafford is a well-connected residential area close to both Manchester United\'s stadium and Trafford Park industrial zone. A diverse mix of family homes and private rented properties generates demand across regular cleaning, end of tenancy, and commercial cleaning for the nearby business parks.',
    propertyTypes: 'Terraced houses, semis, modern apartments',
    nearbyAreas: ['whalley-range', 'stretford', 'salford', 'trafford-park'],
    lat: 53.4631,
    lng: -2.2906,
  },

  // ── MANCHESTER TIER 2 ──────────────────────
  {
    slug: 'salford-quays',
    name: 'Salford Quays',
    postcode: 'M50',
    region: 'manchester',
    tier: 2,
    localContext: 'Salford Quays is the home of MediaCityUK and BBC North, drawing a professional workforce and a premium residential market of waterfront apartments. High disposable income and professional lifestyles drive strong demand for regular weekly and fortnightly cleaning services.',
    propertyTypes: 'Waterfront apartments, luxury penthouses, new-build blocks',
    nearbyAreas: ['salford', 'eccles', 'old-trafford', 'manchester-city-centre'],
    lat: 53.4733,
    lng: -2.2981,
  },
  {
    slug: 'eccles',
    name: 'Eccles',
    postcode: 'M30',
    region: 'manchester',
    tier: 2,
    localContext: 'Eccles is a large suburban town on the western edge of Salford with a mix of family housing and rental properties. Lower competition for cleaning services and good Metrolink connectivity makes it an accessible market with growing demand for regular and deep cleaning.',
    propertyTypes: 'Victorian terraces, 1930s semis, new-build estates',
    nearbyAreas: ['salford', 'swinton', 'worsley', 'salford-quays'],
    lat: 53.4833,
    lng: -2.3336,
  },
  {
    slug: 'stretford',
    name: 'Stretford',
    postcode: 'M32',
    region: 'manchester',
    tier: 2,
    localContext: 'Stretford is a family-friendly suburb in Trafford with a strong community feel and predominantly period housing. The area is gentrifying steadily, attracting younger buyers and renters priced out of Chorlton — generating growing demand for deep cleaning and end of tenancy services.',
    propertyTypes: 'Victorian and Edwardian terraces, semis, flats',
    nearbyAreas: ['old-trafford', 'chorlton', 'sale', 'whalley-range'],
    lat: 53.4467,
    lng: -2.3086,
  },
  {
    slug: 'sale',
    name: 'Sale',
    postcode: 'M33',
    region: 'manchester',
    tier: 2,
    localContext: 'Sale is one of Trafford\'s most popular suburban towns, well-connected by Metrolink and attractive to families and commuters. Its affluent residential market and growing number of buy-to-let properties create consistent demand for both domestic and commercial cleaning.',
    propertyTypes: 'Large Edwardian semis, detached family homes, modern apartments',
    nearbyAreas: ['altrincham', 'stretford', 'urmston', 'chorlton'],
    lat: 53.4254,
    lng: -2.3222,
  },
  {
    slug: 'altrincham',
    name: 'Altrincham',
    postcode: 'WA14',
    region: 'manchester',
    tier: 2,
    localContext: 'Altrincham has been transformed by its award-winning market and growing food and hospitality scene, making it one of Greater Manchester\'s most desirable addresses. The premium residential and commercial property market drives high demand for professional regular cleaning and commercial contract services.',
    propertyTypes: 'Large detached homes, Victorian villas, premium apartments',
    nearbyAreas: ['sale', 'hale', 'bowdon', 'timperley'],
    lat: 53.3839,
    lng: -2.3527,
  },
  {
    slug: 'hale',
    name: 'Hale',
    postcode: 'WA15',
    region: 'manchester',
    tier: 2,
    localContext: 'Hale is one of Greater Manchester\'s most affluent villages, popular with footballers, business professionals, and established families. Premium property values and high disposable incomes drive strong demand for regular weekly cleaning and deep cleans in this exclusive market.',
    propertyTypes: 'Large detached homes, luxury conversions, gated developments',
    nearbyAreas: ['altrincham', 'bowdon', 'hale-barns', 'timperley'],
    lat: 53.3753,
    lng: -2.3584,
  },
  {
    slug: 'urmston',
    name: 'Urmston',
    postcode: 'M41',
    region: 'manchester',
    tier: 2,
    localContext: 'Urmston is a popular family suburb in Trafford with a strong community and excellent transport links. A growing market of young families and commuters creates steady demand for regular and deep cleaning services across this well-established residential area.',
    propertyTypes: 'Edwardian and interwar semis, terraces, family detached homes',
    nearbyAreas: ['flixton', 'davyhulme', 'stretford', 'sale'],
    lat: 53.4484,
    lng: -2.3751,
  },
  {
    slug: 'stockport',
    name: 'Stockport',
    postcode: 'SK1',
    region: 'manchester',
    tier: 2,
    localContext: 'Stockport is a major town in Greater Manchester with its own strong residential and commercial market. The growing food and culture scene in the town centre, combined with a large suburban rental market, creates significant demand for both commercial office cleaning and residential services.',
    propertyTypes: 'Victorian terraces, modern apartments, commercial office blocks',
    nearbyAreas: ['heaton-moor', 'cheadle', 'reddish', 'hazel-grove'],
    lat: 53.4083,
    lng: -2.1494,
  },
  {
    slug: 'heaton-moor',
    name: 'Heaton Moor',
    postcode: 'SK4',
    region: 'manchester',
    tier: 2,
    localContext: 'Heaton Moor is a family-led suburb on the Stockport border, well-known for its village high street, period homes, and strong school catchments. Its established professional residential market generates consistent demand for regular and deep cleaning services.',
    propertyTypes: 'Victorian and Edwardian semis, period detached homes, flats',
    nearbyAreas: ['stockport', 'heaton-chapel', 'burnage', 'didsbury'],
    lat: 53.4243,
    lng: -2.1827,
  },
  {
    slug: 'northenden',
    name: 'Northenden',
    postcode: 'M22',
    region: 'manchester',
    tier: 2,
    localContext: 'Northenden is a quiet south Manchester suburb with a mix of family homes and rental properties bordering the River Mersey. Its affordable housing and good links to the airport make it attractive to families and professionals, with steady demand for regular home cleaning.',
    propertyTypes: '1930s semis, bungalows, family terraces',
    nearbyAreas: ['didsbury', 'wythenshawe', 'baguley', 'chorlton'],
    lat: 53.4012,
    lng: -2.2657,
  },
  {
    slug: 'wythenshawe',
    name: 'Wythenshawe',
    postcode: 'M22',
    region: 'manchester',
    tier: 2,
    localContext: 'Wythenshawe is one of Manchester\'s largest residential areas, close to Manchester Airport and well-served by the Metrolink extension. A large social and private rental market, combined with good family housing stock, creates consistent volume demand for affordable regular cleaning.',
    propertyTypes: 'Social housing, council-built semis, private terraces',
    nearbyAreas: ['northenden', 'baguley', 'benchill', 'sharston'],
    lat: 53.3867,
    lng: -2.2602,
  },
  {
    slug: 'longsight',
    name: 'Longsight',
    postcode: 'M12',
    region: 'manchester',
    tier: 2,
    localContext: 'Longsight is a vibrant, culturally diverse community close to Manchester city centre with high rental density along Stockport Road. A large HMO and shared accommodation market creates significant end of tenancy and deep cleaning demand year-round.',
    propertyTypes: 'Victorian terraces, HMOs, bedsits, flats',
    nearbyAreas: ['rusholme', 'fallowfield', 'gorton', 'levenshulme'],
    lat: 53.4548,
    lng: -2.2016,
  },
  {
    slug: 'gorton',
    name: 'Gorton',
    postcode: 'M18',
    region: 'manchester',
    tier: 2,
    localContext: 'Gorton is an east Manchester suburb undergoing steady regeneration with a mix of older housing and newer developments. A large rental population and growing owner-occupier market provides increasing demand for affordable domestic cleaning services.',
    propertyTypes: 'Victorian terraces, 1960s estate houses, new-build flats',
    nearbyAreas: ['levenshulme', 'longsight', 'denton', 'reddish'],
    lat: 53.4600,
    lng: -2.1700,
  },
  {
    slug: 'burnage',
    name: 'Burnage',
    postcode: 'M19',
    region: 'manchester',
    tier: 2,
    localContext: 'Burnage is a predominantly residential south Manchester suburb with a strong sense of community and affordable housing. Bordering Levenshulme and Heaton Moor, it attracts families and first-time buyers who generate steady demand for regular domestic cleaning.',
    propertyTypes: 'Interwar semis, terraces, small detached homes',
    nearbyAreas: ['levenshulme', 'heaton-moor', 'withington', 'didsbury'],
    lat: 53.4315,
    lng: -2.1965,
  },
  {
    slug: 'prestwich',
    name: 'Prestwich',
    postcode: 'M25',
    region: 'manchester',
    tier: 2,
    localContext: 'Prestwich in Bury is a popular north Manchester suburb with good Metrolink links and an increasingly attractive property market. A growing population of young families and professionals drives demand for regular and deep cleaning services.',
    propertyTypes: 'Edwardian semis, 1930s housing, modern apartments',
    nearbyAreas: ['whitefield', 'bury', 'cheetham-hill', 'crumpsall'],
    lat: 53.5334,
    lng: -2.2843,
  },
  {
    slug: 'manchester-city-centre',
    name: 'Manchester City Centre',
    postcode: 'M1',
    region: 'manchester',
    tier: 1,
    localContext: 'Manchester city centre is the commercial heart of the North West, with thousands of apartments in Spinningfields, Ancoats, the Northern Quarter, and Deansgate. High-rise residential blocks and premium rental apartments drive consistent demand for regular cleaning and end of tenancy services from a transient professional population.',
    propertyTypes: 'High-rise apartments, luxury penthouses, studio flats, commercial offices',
    nearbyAreas: ['salford', 'hulme', 'ancoats', 'deansgate'],
    lat: 53.4808,
    lng: -2.2426,
  },

  // ── MANCHESTER TIER 3 ──────────────────────
  {
    slug: 'crumpsall',
    name: 'Crumpsall',
    postcode: 'M8',
    region: 'manchester',
    tier: 3,
    localContext: 'Crumpsall is a north Manchester suburb close to the North Manchester General Hospital, with a large private and social rental market. Steady demand for affordable domestic cleaning from a diverse community of families and renters.',
    propertyTypes: 'Victorian terraces, interwar semis, post-war housing',
    nearbyAreas: ['cheetham-hill', 'moston', 'prestwich', 'whitefield'],
    lat: 53.5149,
    lng: -2.2416,
  },
  {
    slug: 'cheetham-hill',
    name: 'Cheetham Hill',
    postcode: 'M8',
    region: 'manchester',
    tier: 3,
    localContext: 'Cheetham Hill is a culturally diverse inner Manchester suburb with a thriving wholesale trade district and large residential areas. A mix of social and private rental properties creates consistent demand for domestic cleaning and end of tenancy services.',
    propertyTypes: 'Victorian terraces, purpose-built flats, HMOs',
    nearbyAreas: ['crumpsall', 'moston', 'manchester-city-centre', 'salford'],
    lat: 53.5049,
    lng: -2.2360,
  },
  {
    slug: 'moston',
    name: 'Moston',
    postcode: 'M40',
    region: 'manchester',
    tier: 3,
    localContext: 'Moston is a north Manchester neighbourhood with affordable family housing and a strong community feel. An accessible, lower-competition market for domestic cleaning with growing demand from the local rental sector.',
    propertyTypes: 'Victorian terraces, 1930s semis, council-built housing',
    nearbyAreas: ['newton-heath', 'cheetham-hill', 'failsworth', 'oldham'],
    lat: 53.5098,
    lng: -2.1793,
  },
  {
    slug: 'swinton',
    name: 'Swinton',
    postcode: 'M27',
    region: 'manchester',
    tier: 3,
    localContext: 'Swinton in Salford is a well-connected suburban town with strong Metrolink and bus links. Growing family housing market and accessible rental sector create consistent demand for domestic cleaning at competitive prices.',
    propertyTypes: 'Interwar semis, 1960s estates, modern builds',
    nearbyAreas: ['eccles', 'worsley', 'salford', 'pendlebury'],
    lat: 53.5114,
    lng: -2.3396,
  },
  {
    slug: 'worsley',
    name: 'Worsley',
    postcode: 'M28',
    region: 'manchester',
    tier: 3,
    localContext: 'Worsley is an affluent Salford suburb known for its historic canal and woodland, popular with established families and professionals seeking suburban living with good transport links. Premium domestic cleaning demand from high-value detached homes.',
    propertyTypes: 'Detached family homes, 1930s semis, luxury new builds',
    nearbyAreas: ['eccles', 'swinton', 'boothstown', 'walkden'],
    lat: 53.5033,
    lng: -2.3858,
  },
  {
    slug: 'whitefield',
    name: 'Whitefield',
    postcode: 'M45',
    region: 'manchester',
    tier: 3,
    localContext: 'Whitefield in Bury is a popular suburban area with strong Metrolink connectivity and a growing family housing market. Well-established residential community creates steady demand for regular domestic cleaning services.',
    propertyTypes: 'Edwardian semis, 1930s detached homes, modern apartments',
    nearbyAreas: ['prestwich', 'bury', 'radcliffe', 'cheetham-hill'],
    lat: 53.5518,
    lng: -2.2950,
  },
  {
    slug: 'cheadle',
    name: 'Cheadle',
    postcode: 'SK8',
    region: 'manchester',
    tier: 3,
    localContext: 'Cheadle is a popular Stockport suburb with good schools, excellent transport links, and a mix of period and modern housing popular with families. Steady demand for regular and deep cleaning from an established owner-occupier community.',
    propertyTypes: 'Edwardian and Victorian semis, detached family homes, apartments',
    nearbyAreas: ['stockport', 'gatley', 'heald-green', 'wilmslow'],
    lat: 53.3909,
    lng: -2.2175,
  },
  {
    slug: 'hazel-grove',
    name: 'Hazel Grove',
    postcode: 'SK7',
    region: 'manchester',
    tier: 3,
    localContext: 'Hazel Grove is a Stockport suburb on the A6 corridor with a mix of older housing and modern developments popular with commuters and families. Growing demand for domestic cleaning as the area attracts more professional households.',
    propertyTypes: 'Victorian terraces, 1960s semis, modern detached homes',
    nearbyAreas: ['stockport', 'bramhall', 'davenport', 'marple'],
    lat: 53.3779,
    lng: -2.1190,
  },

  // ── CREWE TIER 1 ──────────────────────────
  {
    slug: 'crewe',
    name: 'Crewe',
    postcode: 'CW1',
    region: 'crewe',
    tier: 1,
    localContext: 'Crewe is Cheshire East\'s largest town, historically built around its famous railway junction and now home to major employers including Bentley Motors. A large and varied property market — from Victorian terraces in the town centre to new-build estates — creates strong and diverse demand for all types of residential and commercial cleaning.',
    propertyTypes: 'Victorian terraces, new-build estates, 1930s semis, commercial offices',
    nearbyAreas: ['nantwich', 'sandbach', 'shavington', 'haslington'],
    lat: 53.0985,
    lng: -2.4414,
  },
  {
    slug: 'nantwich',
    name: 'Nantwich',
    postcode: 'CW5',
    region: 'crewe',
    tier: 1,
    localContext: 'Nantwich is a beautiful historic market town in Cheshire East with a premium property market, excellent schools, and a strong sense of community. Period properties and high-value homes create strong demand for professional regular and deep cleaning from affluent owner-occupiers and the active letting market.',
    propertyTypes: 'Tudor buildings, Georgian townhouses, period semis, new-build executive homes',
    nearbyAreas: ['crewe', 'wistaston', 'wybunbury', 'wrenbury'],
    lat: 53.0672,
    lng: -2.5215,
  },
  {
    slug: 'sandbach',
    name: 'Sandbach',
    postcode: 'CW11',
    region: 'crewe',
    tier: 1,
    localContext: 'Sandbach is a growing Cheshire market town with a mix of historic cobbled streets and modern residential development. Its expanding new-build housing market — particularly around Elworth and Wheelock Heath — drives consistent post-construction cleaning and new-home cleaning demand.',
    propertyTypes: 'New-build estates, period townhouses, family semis',
    nearbyAreas: ['crewe', 'middlewich', 'congleton', 'alsager'],
    lat: 53.1455,
    lng: -2.3619,
  },
  {
    slug: 'middlewich',
    name: 'Middlewich',
    postcode: 'CW10',
    region: 'crewe',
    tier: 1,
    localContext: 'Middlewich is a Cheshire salt town with a growing residential market and lower competition for cleaning services. Its mix of family homes and light industrial premises creates demand for both domestic and commercial cleaning at accessible price points.',
    propertyTypes: 'Victorian terraces, 1960s estates, new residential developments',
    nearbyAreas: ['sandbach', 'crewe', 'northwich', 'holmes-chapel'],
    lat: 53.1885,
    lng: -2.4430,
  },
  {
    slug: 'haslington',
    name: 'Haslington',
    postcode: 'CW1',
    region: 'crewe',
    tier: 1,
    localContext: 'Haslington is a residential village on the eastern edge of Crewe with a strong community identity and predominantly family owner-occupier housing. Low competition and consistent demand from a settled residential population make it an excellent market for regular domestic cleaning.',
    propertyTypes: 'Family semis, detached homes, small private estates',
    nearbyAreas: ['crewe', 'sandbach', 'alsager', 'radway-green'],
    lat: 53.0891,
    lng: -2.4034,
  },
  {
    slug: 'shavington',
    name: 'Shavington',
    postcode: 'CW2',
    region: 'crewe',
    tier: 1,
    localContext: 'Shavington is a popular residential village south of Crewe that has grown considerably in recent years with new housing developments. Its commuter-friendly location and family demographic create strong demand for regular weekly and fortnightly home cleaning.',
    propertyTypes: 'Modern new-build detached homes, family semis, new estates',
    nearbyAreas: ['crewe', 'nantwich', 'willaston', 'wybunbury'],
    lat: 53.0555,
    lng: -2.4624,
  },

  // ── CREWE TIER 2 ──────────────────────────
  {
    slug: 'alsager',
    name: 'Alsager',
    postcode: 'ST7',
    region: 'crewe',
    tier: 2,
    localContext: 'Alsager is a market town on the Staffordshire-Cheshire border with a strong residential community and low competition for cleaning services. Its family-dominated housing market generates steady demand for regular and deep cleaning, particularly around the many owner-occupier estates.',
    propertyTypes: 'Family detached homes, semis, 1960s estates',
    nearbyAreas: ['sandbach', 'crewe', 'kidsgrove', 'congleton'],
    lat: 53.0988,
    lng: -2.3145,
  },
  {
    slug: 'congleton',
    name: 'Congleton',
    postcode: 'CW12',
    region: 'crewe',
    tier: 2,
    localContext: 'Congleton is a market town in south Cheshire with a growing residential market and a strong small business community. Its mix of period town-centre properties and suburban estates creates demand across all residential cleaning services.',
    propertyTypes: 'Georgian and Victorian town houses, suburban semis, new-build developments',
    nearbyAreas: ['sandbach', 'alsager', 'macclesfield', 'biddulph'],
    lat: 53.1629,
    lng: -2.2157,
  },
  {
    slug: 'northwich',
    name: 'Northwich',
    postcode: 'CW8',
    region: 'crewe',
    tier: 2,
    localContext: 'Northwich is a mid-Cheshire town that has seen significant development around the Barons Quay waterfront. Its growing mix of new apartments, family housing, and small business premises creates demand for both residential and commercial cleaning services.',
    propertyTypes: 'Waterfront apartments, Victorian terraces, family semis, office spaces',
    nearbyAreas: ['middlewich', 'winsford', 'hartford', 'knutsford'],
    lat: 53.2580,
    lng: -2.5183,
  },
  {
    slug: 'winsford',
    name: 'Winsford',
    postcode: 'CW7',
    region: 'crewe',
    tier: 2,
    localContext: 'Winsford is a Cheshire town with a large social and affordable private rental market, creating volume demand for end of tenancy, regular, and deep cleaning at competitive price points. Good value properties attract first-time buyers and families.',
    propertyTypes: 'Post-war estates, social housing, 1970s semis, some new builds',
    nearbyAreas: ['northwich', 'middlewich', 'hartford', 'cuddington'],
    lat: 53.1908,
    lng: -2.5252,
  },
  {
    slug: 'holmes-chapel',
    name: 'Holmes Chapel',
    postcode: 'CW4',
    region: 'crewe',
    tier: 2,
    localContext: 'Holmes Chapel is a desirable Cheshire village with strong transport links and an affluent residential community. Premium property values and professional occupiers create demand for regular weekly cleaning and occasional deep cleans.',
    propertyTypes: 'Detached family homes, executive new builds, period cottages',
    nearbyAreas: ['middlewich', 'sandbach', 'knutsford', 'macclesfield'],
    lat: 53.1983,
    lng: -2.3560,
  },
  {
    slug: 'knutsford',
    name: 'Knutsford',
    postcode: 'WA16',
    region: 'crewe',
    tier: 2,
    localContext: 'Knutsford is one of Cheshire\'s most desirable market towns, known for its Georgian architecture, independent shops, and exclusive property market. High household incomes and premium properties drive strong demand for weekly regular cleaning and detailed deep cleans from discerning clients.',
    propertyTypes: 'Georgian townhouses, large detached homes, converted barns, luxury apartments',
    nearbyAreas: ['alderley-edge', 'wilmslow', 'northwich', 'macclesfield'],
    lat: 53.3015,
    lng: -2.3730,
  },
  {
    slug: 'macclesfield',
    name: 'Macclesfield',
    postcode: 'SK10',
    region: 'crewe',
    tier: 2,
    localContext: 'Macclesfield is a historic Cheshire silk town with a growing residential market and strong rail links to Manchester and London. A mix of period terraces, modern apartments, and suburban estates creates diverse demand across all residential cleaning services.',
    propertyTypes: 'Victorian and Edwardian terraces, new-build apartments, family semis',
    nearbyAreas: ['wilmslow', 'congleton', 'knutsford', 'bollington'],
    lat: 53.2593,
    lng: -2.1254,
  },
  {
    slug: 'wilmslow',
    name: 'Wilmslow',
    postcode: 'SK9',
    region: 'crewe',
    tier: 2,
    localContext: 'Wilmslow is Cheshire\'s premium commuter town, home to a highly affluent population of executives, professionals, and sports personalities. Top-tier property values and demanding lifestyle expectations create a premium market for regular weekly cleaning and detailed spring cleans.',
    propertyTypes: 'Large detached homes, executive new builds, luxury apartments, gated developments',
    nearbyAreas: ['alderley-edge', 'handforth', 'knutsford', 'macclesfield'],
    lat: 53.3306,
    lng: -2.2320,
  },
  {
    slug: 'alderley-edge',
    name: 'Alderley Edge',
    postcode: 'SK9',
    region: 'crewe',
    tier: 2,
    localContext: 'Alderley Edge is synonymous with luxury living in Cheshire, home to some of the region\'s most valuable properties and high-profile residents. Ultra-premium demand for meticulous regular cleaning, discreet service, and specialist deep cleans from high-net-worth households.',
    propertyTypes: 'Mansion houses, luxury new builds, converted period properties, gated estates',
    nearbyAreas: ['wilmslow', 'knutsford', 'prestbury', 'macclesfield'],
    lat: 53.3042,
    lng: -2.2260,
  },

  // ── CREWE TIER 3 ──────────────────────────
  {
    slug: 'wistaston',
    name: 'Wistaston',
    postcode: 'CW2',
    region: 'crewe',
    tier: 3,
    localContext: 'Wistaston is a residential village on the south side of Crewe with good schools and a stable family community. Low competition and consistent owner-occupier demand for regular cleaning services.',
    propertyTypes: 'Family semis, detached homes, small private estates',
    nearbyAreas: ['crewe', 'nantwich', 'shavington', 'wybunbury'],
    lat: 53.0793,
    lng: -2.4753,
  },
  {
    slug: 'wybunbury',
    name: 'Wybunbury',
    postcode: 'CW5',
    region: 'crewe',
    tier: 3,
    localContext: 'Wybunbury is a small Cheshire village between Crewe and Nantwich known for its historic leaning tower. A quiet residential community with low cleaning competition and demand from owner-occupier households.',
    propertyTypes: 'Village cottages, farmhouses, rural family homes',
    nearbyAreas: ['nantwich', 'crewe', 'shavington', 'wrenbury'],
    lat: 53.0401,
    lng: -2.4565,
  },
  {
    slug: 'audlem',
    name: 'Audlem',
    postcode: 'CW3',
    region: 'crewe',
    tier: 3,
    localContext: 'Audlem is a picturesque canal-side market village in south Cheshire with period properties and an active community. Very low competition for cleaning services from a residential population of families and retirees.',
    propertyTypes: 'Georgian and Victorian cottages, rural farmhouses, small new builds',
    nearbyAreas: ['nantwich', 'crewe', 'market-drayton'],
    lat: 52.9861,
    lng: -2.5103,
  },
  {
    slug: 'goostrey',
    name: 'Goostrey',
    postcode: 'CW4',
    region: 'crewe',
    tier: 3,
    localContext: 'Goostrey is a sought-after village near Jodrell Bank with premium rural residential properties and excellent transport links. Affluent owner-occupier households generate good demand for regular cleaning despite the rural setting.',
    propertyTypes: 'Detached rural homes, converted barns, executive new builds',
    nearbyAreas: ['holmes-chapel', 'middlewich', 'knutsford', 'congleton'],
    lat: 53.2163,
    lng: -2.3227,
  },
  {
    slug: 'tarporley',
    name: 'Tarporley',
    postcode: 'CW6',
    region: 'crewe',
    tier: 3,
    localContext: 'Tarporley is an elegant Cheshire village with premium property values and a strong community of affluent professionals and families. Premium domestic cleaning demand from high-value period and executive homes.',
    propertyTypes: 'Georgian period homes, detached executive houses, rural cottages',
    nearbyAreas: ['northwich', 'knutsford', 'winsford', 'bunbury'],
    lat: 53.1685,
    lng: -2.6704,
  },
  {
    slug: 'wrenbury',
    name: 'Wrenbury',
    postcode: 'CW5',
    region: 'crewe',
    tier: 3,
    localContext: 'Wrenbury is a quiet village near Nantwich known for its working canal drawbridge and rural character. Owner-occupier community with very low local cleaning competition — an ideal gap in the market for a service-area page.',
    propertyTypes: 'Village cottages, farmhouses, period rural homes',
    nearbyAreas: ['nantwich', 'audlem', 'malpas'],
    lat: 53.0153,
    lng: -2.5768,
  },
  {
    slug: 'handforth',
    name: 'Handforth',
    postcode: 'SK9',
    region: 'crewe',
    tier: 3,
    localContext: 'Handforth is a commuter suburb between Wilmslow and Stockport with steady family residential demand. Growing demand for regular cleaning from professional households with good disposable income and busy schedules.',
    propertyTypes: 'Interwar and modern semis, small detached homes, new-build estates',
    nearbyAreas: ['wilmslow', 'cheadle', 'stockport', 'alderley-edge'],
    lat: 53.3555,
    lng: -2.2143,
  },
  {
    slug: 'bunbury',
    name: 'Bunbury',
    postcode: 'CW6',
    region: 'crewe',
    tier: 3,
    localContext: 'Bunbury is a quintessential Cheshire village with premium rural residential property and very low local service competition. Ideal for hyper-local SEO targeting high-value cleaning enquiries from affluent rural households.',
    propertyTypes: 'Period cottages, farmhouses, luxury rural conversions',
    nearbyAreas: ['tarporley', 'nantwich', 'crewe'],
    lat: 53.1167,
    lng: -2.6219,
  },
  {
    slug: 'bury',
    name: 'Bury',
    postcode: 'BL9',
    region: 'manchester',
    tier: 3,
    localContext: 'Bury is a market town north of Manchester famous for its outdoor market and black pudding. A large suburban area with strong family housing and rental demand, Bury is an underserved market for professional domestic cleaning services.',
    propertyTypes: 'Victorian terraces, interwar semis, 1970s estates',
    nearbyAreas: ['prestwich', 'whitefield', 'crumpsall'],
    lat: 53.5933,
    lng: -2.2981,
  },
  {
    slug: 'trafford-park',
    name: 'Trafford Park',
    postcode: 'M17',
    region: 'manchester',
    tier: 2,
    localContext: 'Trafford Park is one of Europe\'s largest industrial estates, home to major employers and logistics hubs. Strong commercial cleaning demand from warehouse facilities, distribution centres, and office spaces within this vast employment area.',
    propertyTypes: 'Commercial offices, warehouses, light industrial units',
    nearbyAreas: ['old-trafford', 'salford-quays', 'eccles', 'stretford'],
    lat: 53.4625,
    lng: -2.3204,
  },
  {
    slug: 'heaton-chapel',
    name: 'Heaton Chapel',
    postcode: 'SK4',
    region: 'manchester',
    tier: 3,
    localContext: 'Heaton Chapel sits between Stockport and Manchester with excellent rail links and a popular commuter residential market. Period terraces and family homes create steady demand for regular and deep cleaning from professional households.',
    propertyTypes: 'Victorian terraces, Edwardian semis, flat conversions',
    nearbyAreas: ['heaton-moor', 'stockport', 'burnage', 'levenshulme'],
    lat: 53.4264,
    lng: -2.1737,
  },

  // ── MISSING MANCHESTER LOCATIONS ──────────────────────────────────
  {
    slug: 'ardwick',
    name: 'Ardwick',
    postcode: 'M12',
    region: 'manchester',
    tier: 3,
    localContext: 'Ardwick is an inner Manchester neighbourhood close to the city centre and the Manchester Velodrome. A mix of regeneration projects and established housing provides growing demand for domestic cleaning from a diverse renting population.',
    propertyTypes: 'Victorian terraces, new-build apartments, social housing',
    nearbyAreas: ['longsight', 'manchester-city-centre', 'hulme', 'gorton'],
    lat: 53.4697,
    lng: -2.2122,
  },
  {
    slug: 'harpurhey',
    name: 'Harpurhey',
    postcode: 'M9',
    region: 'manchester',
    tier: 3,
    localContext: 'Harpurhey is a north Manchester neighbourhood with affordable housing and a large social and private rental market. Low competition for cleaning services makes it an accessible market for thefamgroup\'s domestic cleaning services.',
    propertyTypes: 'Victorian terraces, post-war housing, social housing blocks',
    nearbyAreas: ['moston', 'crumpsall', 'cheetham-hill', 'newton-heath'],
    lat: 53.5061,
    lng: -2.2218,
  },
  {
    slug: 'spinningfields',
    name: 'Spinningfields',
    postcode: 'M3',
    region: 'manchester',
    tier: 1,
    localContext: 'Spinningfields is Manchester\'s premier business and finance district, home to leading law firms, banks, and the Manchester Civil Justice Centre. High demand for professional out-of-hours office cleaning contracts from a dense concentration of corporate tenants.',
    propertyTypes: 'Premium office blocks, luxury apartments, commercial high-rises',
    nearbyAreas: ['manchester-city-centre', 'deansgate', 'salford', 'ancoats'],
    lat: 53.4798,
    lng: -2.2524,
  },
  {
    slug: 'ancoats',
    name: 'Ancoats',
    postcode: 'M4',
    region: 'manchester',
    tier: 1,
    localContext: 'Ancoats is one of Manchester\'s most fashionable neighbourhoods, a former industrial quarter now packed with premium apartments, restaurants, and independent businesses. High concentrations of young professionals create strong demand for regular home cleaning and Airbnb turnaround services.',
    propertyTypes: 'Converted mill apartments, modern high-rise flats, commercial units',
    nearbyAreas: ['manchester-city-centre', 'northern-quarter', 'hulme', 'ardwick'],
    lat: 53.4841,
    lng: -2.2264,
  },
  {
    slug: 'northern-quarter',
    name: 'Northern Quarter',
    postcode: 'M4',
    region: 'manchester',
    tier: 1,
    localContext: 'The Northern Quarter is Manchester\'s creative and cultural hub, filled with independent bars, studios, and apartment developments. A young, professional renting population drives consistent demand for regular domestic cleaning and end of tenancy services.',
    propertyTypes: 'Converted warehouse apartments, modern studio flats, commercial premises',
    nearbyAreas: ['ancoats', 'manchester-city-centre', 'cheetham-hill', 'ardwick'],
    lat: 53.4843,
    lng: -2.2362,
  },
  {
    slug: 'deansgate',
    name: 'Deansgate',
    postcode: 'M3',
    region: 'manchester',
    tier: 1,
    localContext: 'Deansgate is one of Manchester\'s most prestigious addresses, home to luxury apartments, high-end hotels, and major commercial office buildings. Premium residential and commercial cleaning demand from affluent occupants and corporate tenants along this landmark street.',
    propertyTypes: 'Luxury penthouses, high-end apartment blocks, commercial offices',
    nearbyAreas: ['spinningfields', 'manchester-city-centre', 'salford', 'castlefield'],
    lat: 53.4758,
    lng: -2.2506,
  },
  {
    slug: 'piccadilly',
    name: 'Piccadilly',
    postcode: 'M1',
    region: 'manchester',
    tier: 1,
    localContext: 'Piccadilly is the transport and commercial heart of Manchester, anchored by Manchester Piccadilly train station. A rapidly growing residential market of apartments and serviced accommodation around the station creates strong demand for regular cleaning and Airbnb turnaround services.',
    propertyTypes: 'Modern apartments, serviced accommodation, commercial offices',
    nearbyAreas: ['northern-quarter', 'manchester-city-centre', 'ancoats', 'ardwick'],
    lat: 53.4774,
    lng: -2.2309,
  },

  // ── MISSING CREWE / CHESHIRE LOCATIONS ────────────────────────────
  {
    slug: 'radway-green',
    name: 'Radway Green',
    postcode: 'CW2',
    region: 'crewe',
    tier: 3,
    localContext: 'Radway Green is a small residential village between Crewe and Alsager, home to a quiet community of families and professionals. Very low local cleaning competition from this underserved Cheshire East village makes it ideal for hyper-local search targeting.',
    propertyTypes: 'Family semis, detached homes, village properties',
    nearbyAreas: ['alsager', 'crewe', 'haslington', 'sandbach'],
    lat: 53.0837,
    lng: -2.3486,
  },
  {
    slug: 'prestbury',
    name: 'Prestbury',
    postcode: 'SK10',
    region: 'crewe',
    tier: 2,
    localContext: 'Prestbury is one of Cheshire\'s wealthiest villages, consistently listed among the UK\'s most expensive postcodes outside London. An ultra-affluent residential community with large detached properties creates premium demand for meticulous regular cleaning and specialist services.',
    propertyTypes: 'Luxury detached homes, converted farmhouses, gated estates',
    nearbyAreas: ['macclesfield', 'alderley-edge', 'wilmslow', 'knutsford'],
    lat: 53.2897,
    lng: -2.1434,
  },

  // ── CHESHIRE / CHESTER ────────────────────────────────────────────
  {
    slug: 'chester',
    name: 'Chester',
    postcode: 'CH1',
    region: 'crewe',
    tier: 1,
    localContext: 'Chester is one of Britain\'s most historic walled cities, with a thriving tourism economy and a strong mix of period residences, student lettings, and upscale properties near the Rows. High footfall in the short-let sector and premium owner-occupied homes drive significant demand for end-of-tenancy, Airbnb reset, and regular residential cleaning.',
    propertyTypes: 'Georgian townhouses, Victorian terraces, modern apartments, student lets',
    nearbyAreas: ['ellesmere-port', 'crewe', 'nantwich', 'wrexham'],
    lat: 53.1939,
    lng: -2.8931,
  },
  {
    slug: 'ellesmere-port',
    name: 'Ellesmere Port',
    postcode: 'CH65',
    region: 'crewe',
    tier: 2,
    localContext: 'Ellesmere Port is a growing Cheshire West town with a large social and private rental sector alongside new residential developments. Strong end-of-tenancy and regular residential demand from an affordable housing market close to the Mersey.',
    propertyTypes: '1960s–70s estates, modern new-builds, rented terraces',
    nearbyAreas: ['chester', 'widnes', 'runcorn', 'birkenhead'],
    lat: 53.2790,
    lng: -2.8975,
  },

  // ── LIVERPOOL REGION ─────────────────────────────────────────────
  {
    slug: 'liverpool',
    name: 'Liverpool',
    postcode: 'L1',
    region: 'liverpool',
    tier: 1,
    localContext: 'Liverpool is a major northern city with a booming rental market — particularly around the Baltic Triangle, Waterfront, and student zones near the universities. Strong year-round demand for end-of-tenancy, Airbnb reset, and office cleaning driven by a thriving hospitality and creative economy.',
    propertyTypes: 'Georgian townhouses, converted warehouses, modern city apartments, student HMOs',
    nearbyAreas: ['birkenhead', 'bootle', 'wallasey', 'st-helens'],
    lat: 53.4084,
    lng: -2.9916,
  },
  {
    slug: 'warrington',
    name: 'Warrington',
    postcode: 'WA1',
    region: 'liverpool',
    tier: 1,
    localContext: 'Warrington is a thriving commercial and residential hub midway between Manchester and Liverpool. Its large business park sector and growing commuter housing market create consistent demand for office, commercial, and end-of-tenancy cleaning across all property types.',
    propertyTypes: 'New-build estates, 1970s–80s semis, commercial offices, business parks',
    nearbyAreas: ['widnes', 'runcorn', 'liverpool', 'manchester'],
    lat: 53.3900,
    lng: -2.5970,
  },
  {
    slug: 'birkenhead',
    name: 'Birkenhead',
    postcode: 'CH41',
    region: 'liverpool',
    tier: 2,
    localContext: 'Birkenhead is the largest town on the Wirral Peninsula, with a large private rental market and a mix of Victorian terraces and 1960s housing. Its proximity to Liverpool via the Mersey Tunnel makes it an expanding market for affordable end-of-tenancy and regular domestic cleaning.',
    propertyTypes: 'Victorian terraces, 1960s flats, period semis',
    nearbyAreas: ['liverpool', 'wallasey', 'ellesmere-port', 'chester'],
    lat: 53.3936,
    lng: -3.0149,
  },
  {
    slug: 'st-helens',
    name: 'St Helens',
    postcode: 'WA9',
    region: 'liverpool',
    tier: 2,
    localContext: 'St Helens is a large Merseyside town with a growing new-build housing market and a strong community identity. Increased investment in residential development and a recovering commercial sector create growing cleaning demand for both domestic and light commercial clients.',
    propertyTypes: 'New-build housing, interwar semis, 1960s estates, commercial units',
    nearbyAreas: ['warrington', 'liverpool', 'wigan', 'widnes'],
    lat: 53.4542,
    lng: -2.7374,
  },
  {
    slug: 'widnes',
    name: 'Widnes',
    postcode: 'WA8',
    region: 'liverpool',
    tier: 2,
    localContext: 'Widnes sits on the River Mersey between Warrington and Liverpool and has a large, affordable private rental market. Its proximity to both cities and underserved local cleaning competition make it ideal for end-of-tenancy and regular domestic cleaning growth.',
    propertyTypes: 'Terrace rows, interwar semis, 1980s housing estates',
    nearbyAreas: ['runcorn', 'warrington', 'liverpool', 'st-helens'],
    lat: 53.3626,
    lng: -2.7298,
  },
  {
    slug: 'runcorn',
    name: 'Runcorn',
    postcode: 'WA7',
    region: 'liverpool',
    tier: 2,
    localContext: 'Runcorn is a new town development that expanded significantly in the 1970s with a large social and private rental market. Its large-scale housing estates and industrial heritage create steady demand for affordable domestic and end-of-tenancy cleaning services.',
    propertyTypes: '1970s new-town houses, terrace rows, modern rentals',
    nearbyAreas: ['widnes', 'warrington', 'ellesmere-port', 'chester'],
    lat: 53.3416,
    lng: -2.7346,
  },

  // ── STOKE-ON-TRENT REGION ────────────────────────────────────────
  {
    slug: 'stoke-on-trent',
    name: 'Stoke-on-Trent',
    postcode: 'ST1',
    region: 'stoke',
    tier: 1,
    localContext: 'Stoke-on-Trent is a federation of six towns — the Potteries — with a large, affordable housing market and a significant student population from Keele and Staffordshire universities. Strong demand for end-of-tenancy, student property cleaning, and regular domestic services across a wide spread of rental properties.',
    propertyTypes: 'Victorian terraces, interwar semis, 1960s–70s estates, student HMOs, new-builds',
    nearbyAreas: ['newcastle-under-lyme', 'hanley', 'congleton', 'stafford'],
    lat: 53.0027,
    lng: -2.1794,
  },
  {
    slug: 'newcastle-under-lyme',
    name: 'Newcastle-under-Lyme',
    postcode: 'ST5',
    region: 'stoke',
    tier: 2,
    localContext: 'Newcastle-under-Lyme is a market town closely linked to Stoke-on-Trent and home to Keele University — one of the UK\'s largest campus universities. A thriving student rental market alongside established family housing creates high end-of-tenancy cleaning demand throughout the academic year.',
    propertyTypes: 'Student HMOs, Victorian terraces, family semis, campus accommodation',
    nearbyAreas: ['stoke-on-trent', 'stafford', 'crewe', 'congleton'],
    lat: 53.0115,
    lng: -2.2277,
  },
  {
    slug: 'stafford',
    name: 'Stafford',
    postcode: 'ST16',
    region: 'stoke',
    tier: 2,
    localContext: 'Stafford is Staffordshire\'s county town with a prosperous commuter market and a mix of period and modern residential properties. Its location on the West Coast Main Line and strong professional demographic create consistent demand for regular domestic and commercial cleaning.',
    propertyTypes: 'Georgian townhouses, Victorian semis, modern commuter estates',
    nearbyAreas: ['stoke-on-trent', 'newcastle-under-lyme', 'cannock', 'lichfield'],
    lat: 52.8066,
    lng: -2.1185,
  },

  // ── CARLISLE REGION ──────────────────────────────────────────────
  {
    slug: 'carlisle',
    name: 'Carlisle',
    postcode: 'CA1',
    region: 'carlisle',
    tier: 1,
    localContext: 'Carlisle is the largest city in Cumbria and the main commercial and residential centre for the North West\'s most northerly reach. Its growing rental market, student population at the University of Cumbria, and proximity to the Lake District tourism economy drive demand for end-of-tenancy, Airbnb reset, and regular domestic cleaning.',
    propertyTypes: 'Victorian terraces, interwar semis, student lets, modern city apartments',
    nearbyAreas: ['penrith', 'whitehaven', 'kendal', 'hexham'],
    lat: 54.8951,
    lng: -2.9382,
  },
  {
    slug: 'penrith',
    name: 'Penrith',
    postcode: 'CA11',
    region: 'carlisle',
    tier: 2,
    localContext: 'Penrith is a prosperous Cumbrian market town on the edge of the Lake District National Park. A buoyant holiday-let and Airbnb market — with properties commanding premium nightly rates — creates strong repeat demand for professional Airbnb turnovers and end-of-tenancy cleaning.',
    propertyTypes: 'Stone cottages, Georgian townhouses, holiday lets, family semis',
    nearbyAreas: ['carlisle', 'kendal', 'keswick', 'appleby'],
    lat: 54.6640,
    lng: -2.7543,
  },
]

// ─────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────

export function getService(slug: string): ServiceData | undefined {
  return SERVICES.find(s => s.slug === slug)
}

export function getLocation(slug: string): LocationData | undefined {
  return LOCATIONS.find(l => l.slug === slug)
}

export function getAllPageParams() {
  return SERVICES.flatMap(service =>
    LOCATIONS.map(location => ({
      service: service.slug,
      location: location.slug,
    }))
  )
}

export function interpolate(template: string, location: LocationData): string {
  return template
    .replace(/\{location\}/g, location.name)
    .replace(/\{postcode\}/g, location.postcode)
}

// Contact details — single source of truth
export const CONTACT = {
  phone: '07767 759 013',
  phoneTel: 'tel:07767759013',
  whatsapp: 'https://wa.me/447767759013',
  email: 'info@thefamgroup.uk',
  website: 'thefamgroup.uk',
  siteUrl: 'https://www.thefamgroup.uk',
  businessName: 'thefamgroup',
  address: 'Manchester & Crewe, UK',
}
